<?php





session_start();
/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

require_once("includes/functions.php");

global $dbconn;
$dbconn = new PDO('mysql:host='.$config['dspdb_host'].';dbname='.$config['dspdb_name'].';charset=utf8mb4', $config['dspdb_user'], $config['dspdb_pass']);

if (!empty($_SESSION['cms'])) {
    $users = authenticate($_SESSION['cms_Username']);
}




$rules_array = array(
0 => "None",
1 => "Subjobs Allowed",
2 => "Can Lose EXP",
4 => "Removed After 3 Minutes",
8 => "Spawns Treasure On Win",
10 => "Maat Fight",
);

$jobs = array(
0 => "",
1 => "war",
2 => "mnk",
3 => "whm",
4 => "blm",
5 => "rdm",
6 => "thf",
7 => "pld",
8 => "drk",
9 => "bst",
10 => "brd",
11 => "rng",
12 => "sam",
13 => "nin",
14 => "drg",
15 => "smn",
16 => "blu",
17 => "cor",
18 => "pup",
19 => "dnc",
20 => "sch",
21 => "geo",
22 => "run"
);

$titles=array(
"None"=>0,
"FODDERCHIEF_FLAYER"=>1,
"WARCHIEF_WRECKER"=>2,
"DREAD_DRAGON_SLAYER"=>3,
"OVERLORD_EXECUTIONER"=>4,
"DARK_DRAGON_SLAYER"=>5,
"ADAMANTKING_KILLER"=>6,
"BLACK_DRAGON_SLAYER"=>7,
"MANIFEST_MAULER"=>8,
"BEHEMOTHS_BANE"=>9,
"ARCHMAGE_ASSASSIN"=>10,
"HELLSBANE"=>11,
"GIANT_KILLER"=>12,
"LICH_BANISHER"=>13,
"JELLYBANE"=>14,
"BOGEYDOWNER"=>15,
"BEAKBENDER"=>16,
"SKULLCRUSHER"=>17,
"MORBOLBANE"=>18,
"GOLIATH_KILLER"=>19,
"MARYS_GUIDE"=>20,
"SIMURGH_POACHER"=>21,
"ROC_STAR"=>22,
"SERKET_BREAKER"=>23,
"CASSIENOVA"=>24,
"THE_HORNSPLITTER"=>25,
"TORTOISE_TORTURER"=>26,
"MON_CHERRY"=>27,
"BEHEMOTH_DETHRONER"=>28,
"THE_VIVISECTOR"=>29,
"DRAGON_ASHER"=>30,
"EXPEDITIONARY_TROOPER"=>31,
"BEARER_OF_THE_WISEWOMANS_HOPE"=>32,
"BEARER_OF_THE_EIGHT_PRAYERS"=>33,
"LIGHTWEAVER"=>34,
"DESTROYER_OF_ANTIQUITY"=>35,
"SEALER_OF_THE_PORTAL_OF_THE_GODS"=>36,
"BURIER_OF_THE_ILLUSION"=>37,
"--Unused"=>38,
"FAMILY_COUNSELOR"=>39,
"--Unused"=>40,
"GREAT_GRAPPLER_SCORPIO"=>41,
"BOND_FIXER"=>42,
"VAMPIRE_HUNTER_DMINUS"=>43,
"SHEEPS_MILK_DELIVERER"=>44,
"BEAN_CUISINE_SALTER"=>45,
"TOTAL_LOSER"=>46,
"DOCTOR_SHANTOTTOS_FLAVOR_OF_THE_MONTH"=>47,
"PILGRIM_TO_HOLLA"=>48,
"PILGRIM_TO_DEM"=>49,
"PILGRIM_TO_MEA"=>50,
"DAYBREAK_GAMBLER"=>51,
"THE_PIOUS_ONE"=>52,
"A_MOSS_KIND_PERSON"=>53,
"ENTRANCE_DENIED"=>54,
"APIARIST"=>55,
"RABBITER"=>56,
"ROYAL_GRAVE_KEEPER"=>57,
"COURIER_EXTRAORDINAIRE"=>58,
"RONFAURIAN_RESCUER"=>59,
"PICKPOCKET_PINCHER"=>60,
"FANG_FINDER"=>61,
"FAITH_LIKE_A_CANDLE"=>62,
"THE_PURE_ONE"=>63,
"LOST_CHILD_OFFICER"=>64,
"SILENCER_OF_THE_LAMBS"=>65,
"LOST_AMP_FOUND_OFFICER"=>66,
"GREEN_GROCER"=>67,
"THE_BENEVOLENT_ONE"=>68,
"KNIGHT_IN_TRAINING"=>69,
"LIZARD_SKINNER"=>70,
"BUG_CATCHER"=>71,
"SPELUNKER"=>72,
"ARMS_TRADER"=>73,
"TRAVELING_MEDICINE_MAN"=>74,
"CAT_SKINNER"=>75,
"CARP_DIEM"=>76,
"ADVERTISING_EXECUTIVE"=>77,
"THIRDRATE_ORGANIZER"=>78,
"SECONDRATE_ORGANIZER"=>79,
"FIRSTRATE_ORGANIZER"=>80,
"BASTOK_WELCOMING_COMMITTEE"=>81,
"SHELL_OUTER"=>82,
"BUCKET_FISHER"=>83,
"PURSUER_OF_THE_PAST"=>84,
"PURSUER_OF_THE_TRUTH"=>85,
"MOMMYS_HELPER"=>86,
"HOT_DOG"=>87,
"STAMPEDER"=>88,
"QIJIS_FRIEND"=>89,
"QIJIS_RIVAL"=>90,
"CONTEST_RIGGER"=>91,
"RINGBEARER"=>92,
"KULATZ_BRIDGE_COMPANION"=>93,
"BEADEAUX_SURVEYOR"=>94,
"AVENGER"=>95,
"TREASURE_SCAVENGER"=>96,
"AIRSHIP_DENOUNCER"=>97,
"ZERUHN_SWEEPER"=>98,
"TEARJERKER"=>99,
"CRAB_CRUSHER"=>100,
"STAR_OF_IFRIT"=>101,
"SORROW_DROWNER"=>102,
"BRYGIDAPPROVED"=>103,
"DRACHENFALL_ASCETIC"=>104,
"STEAMING_SHEEP_REGULAR"=>105,
"PURPLE_BELT"=>106,
"GUSTABERG_TOURIST"=>107,
"SAND_BLASTER"=>108,
"BLACK_DEATH"=>109,
"--Unused"=>110,
"FRESH_NORTH_WINDS_RECRUIT"=>111,
"NEW_BEST_OF_THE_WEST_RECRUIT"=>112,
"NEW_BUUMAS_BOOMERS_RECRUIT"=>113,
"HEAVENS_TOWER_GATEHOUSE_RECRUIT"=>114,
"CAT_BURGLAR_GROUPIE"=>115,
"CRAWLER_CULLER"=>116,
"SAVIOR_OF_KNOWLEDGE"=>117,
"STARORDAINED_WARRIOR"=>118,
"LOWER_THAN_THE_LOWEST_TUNNEL_WORM"=>119,
"STAR_ONION_BRIGADE_MEMBER"=>120,
"STAR_ONION_BRIGADIER"=>121,
"QUICK_FIXER"=>122,
"FAKEMOUSTACHED_INVESTIGATOR"=>123,
"HAKKURURINKURUS_BENEFACTOR"=>124,
"SOB_SUPER_HERO"=>125,
"EDITORS_HATCHET_MAN"=>126,
"DOCTOR_SHANTOTTOS_GUINEA_PIG"=>127,
"SPOILSPORT"=>128,
"SUPER_MODEL"=>129,
"GHOSTIE_BUSTER"=>130,
"NIGHT_SKY_NAVIGATOR"=>131,
"FAST_FOOD_DELIVERER"=>132,
"CUPIDS_FLORIST"=>133,
"TARUTARU_MURDER_SUSPECT"=>134,
"HEXER_VEXER"=>135,
"CARDIAN_TUTOR"=>136,
"DELIVERER_OF_TEARFUL_NEWS"=>137,
"FOSSILIZED_SEA_FARER"=>138,
"DOWN_PIPER_PIPEUPPERER"=>139,
"KISSER_MAKEUPPER"=>140,
"TIMEKEEPER"=>141,
"FORTUNETELLER_IN_TRAINING"=>142,
"TORCHBEARER"=>143,
"TENSHODO_MEMBER"=>144,
"CHOCOBO_TRAINER"=>145,
"BRINGER_OF_BLISS"=>146,
"ACTIVIST_FOR_KINDNESS"=>147,
"ENVOY_TO_THE_NORTH"=>148,
"EXORCIST_IN_TRAINING"=>149,
"PROFESSIONAL_LOAFER"=>150,
"CLOCK_TOWER_PRESERVATIONIST"=>151,
"LIFE_SAVER"=>152,
"FOOLS_ERRAND_RUNNER"=>153,
"CARD_COLLECTOR"=>154,
"RESEARCHER_OF_CLASSICS"=>155,
"STREET_SWEEPER"=>156,
"MERCY_ERRAND_RUNNER"=>157,
"TWOS_COMPANY"=>158,
"BELIEVER_OF_ALTANA"=>159,
"TRADER_OF_MYSTERIES"=>160,
"TRADER_OF_ANTIQUITIES"=>161,
"TRADER_OF_RENOWN"=>162,
"BROWN_BELT"=>163,
"HORIZON_BREAKER"=>164,
"GOBLINS_EXCLUSIVE_FASHION_MANNEQUIN"=>165,
"SUMMIT_BREAKER"=>166,
"SKY_BREAKER"=>167,
"CLOUD_BREAKER"=>168,
"STAR_BREAKER"=>169,
"GREEDALOX"=>170,
"CERTIFIED_RHINOSTERY_VENTURER"=>171,
"CORDON_BLEU_FISHER"=>172,
"ACE_ANGLER"=>173,
"LU_SHANGLIKE_FISHER_KING"=>174,
"MATCHMAKER"=>175,
"ECOLOGIST"=>176,
"LIL_CUPID"=>177,
"THE_LOVE_DOCTOR"=>178,
"SAVIOR_OF_LOVE"=>179,
"HONORARY_CITIZEN_OF_SELBINA"=>180,
"PURVEYOR_IN_TRAINING"=>181,
"ONESTAR_PURVEYOR"=>182,
"TWOSTAR_PURVEYOR"=>183,
"THREESTAR_PURVEYOR"=>184,
"FOURSTAR_PURVEYOR"=>185,
"FIVESTAR_PURVEYOR"=>186,
"DOCTOR_YORANORAN_SUPPORTER"=>187,
"DOCTOR_SHANTOTTO_SUPPORTER"=>188,
"PROFESSOR_KORUMORU_SUPPORTER"=>189,
"RAINBOW_WEAVER"=>190,
"SHADOW_WALKER"=>191,
"HEIR_TO_THE_HOLY_CREST"=>192,
"BUSHIDO_BLADE"=>193,
"--Unused"=>194,
"PARAGON_OF_PALADIN_EXCELLENCE"=>195,
"PARAGON_OF_BEASTMASTER_EXCELLENCE"=>196,
"PARAGON_OF_RANGER_EXCELLENCE"=>197,
"PARAGON_OF_DARK_KNIGHT_EXCELLENCE"=>198,
"PARAGON_OF_BARD_EXCELLENCE"=>199,
"PARAGON_OF_SAMURAI_EXCELLENCE"=>200,
"PARAGON_OF_DRAGOON_EXCELLENCE"=>201,
"PARAGON_OF_NINJA_EXCELLENCE"=>202,
"PARAGON_OF_SUMMONER_EXCELLENCE"=>203,
"--Unused"=>204,
"--Unused"=>205,
"NEW_ADVENTURER"=>206,
"CERTIFIED_ADVENTURER"=>207,
"SHADOW_BANISHER"=>208,
"TRIED_AND_TESTED_KNIGHT"=>209,
"DARK_SIDER"=>210,
"THE_FANGED_ONE"=>211,
"HAVE_WINGS_WILL_FLY"=>212,
"ANIMAL_TRAINER"=>213,
"WANDERING_MINSTREL"=>214,
"MOGS_MASTER"=>215,
"MOGS_KIND_MASTER"=>216,
"MOGS_EXCEPTIONALLY_KIND_MASTER"=>217,
"PARAGON_OF_WARRIOR_EXCELLENCE"=>218,
"PARAGON_OF_MONK_EXCELLENCE"=>219,
"PARAGON_OF_RED_MAGE_EXCELLENCE"=>220,
"PARAGON_OF_THIEF_EXCELLENCE"=>221,
"PARAGON_OF_BLACK_MAGE_EXCELLENCE"=>222,
"PARAGON_OF_WHITE_MAGE_EXCELLENCE"=>223,
"MOGS_LOVING_MASTER"=>224,
"--Unused"=>225,
"ROYAL_ARCHER"=>226,
"ROYAL_SPEARMAN"=>227,
"ROYAL_SQUIRE"=>228,
"ROYAL_SWORDSMAN"=>229,
"ROYAL_CAVALIER"=>230,
"ROYAL_GUARD"=>231,
"GRAND_KNIGHT_OF_THE_REALM"=>232,
"GRAND_TEMPLE_KNIGHT"=>233,
"RESERVE_KNIGHT_CAPTAIN"=>234,
"ELITE_ROYAL_GUARD"=>235,
"LEGIONNAIRE"=>236,
"DECURION"=>237,
"CENTURION"=>238,
"JUNIOR_MUSKETEER"=>239,
"SENIOR_MUSKETEER"=>240,
"MUSKETEER_COMMANDER"=>241,
"GOLD_MUSKETEER"=>242,
"PRAEFECTUS"=>243,
"SENIOR_GOLD_MUSKETEER"=>244,
"PRAEFECTUS_CASTRORUM"=>245,
"FREESWORD"=>246,
"MERCENARY"=>247,
"MERCENARY_CAPTAIN"=>248,
"COMBAT_CASTER"=>249,
"TACTICIAN_MAGICIAN"=>250,
"WISE_WIZARD"=>251,
"PATRIARCH_PROTECTOR"=>252,
"CASTER_CAPTAIN"=>253,
"MASTER_CASTER"=>254,
"MERCENARY_MAJOR"=>255,
"FUGITIVE_MINISTER_BOUNTY_HUNTER"=>256,
"KING_OF_THE_OPOOPOS"=>257,
"EXCOMMUNICATE_OF_KAZHAM"=>258,
"KAZHAM_CALLER"=>259,
"DREAM_DWELLER"=>260,
"APPRENTICE_SOMMELIER"=>261,
"DESERT_HUNTER"=>262,
"SEEKER_OF_TRUTH"=>263,
"KUFTAL_TOURIST"=>264,
"THE_IMMORTAL_FISHER_LU_SHANG"=>265,
"LOOKS_SUBLIME_IN_A_SUBLIGAR"=>266,
"LOOKS_GOOD_IN_LEGGINGS"=>267,
"HONORARY_DOCTORATE_MAJORING_IN_TONBERRIES"=>268,
"TREASUREHOUSE_RANSACKER"=>269,
"CRACKER_OF_THE_SECRET_CODE"=>270,
"BLACK_MARKETEER"=>271,
"ACQUIRER_OF_ANCIENT_ARCANUM"=>272,
"YA_DONE_GOOD"=>273,
"HEIR_OF_THE_GREAT_FIRE"=>274,
"HEIR_OF_THE_GREAT_EARTH"=>275,
"HEIR_OF_THE_GREAT_WATER"=>276,
"HEIR_OF_THE_GREAT_WIND"=>277,
"HEIR_OF_THE_GREAT_ICE"=>278,
"HEIR_OF_THE_GREAT_LIGHTNING"=>279,
"GUIDER_OF_SOULS_TO_THE_SANCTUARY"=>280,
"BEARER_OF_BONDS_BEYOND_TIME"=>281,
"FRIEND_OF_THE_OPOOPOS"=>282,
"HERO_ON_BEHALF_OF_WINDURST"=>283,
"VICTOR_OF_THE_BALGA_CONTEST"=>284,
"GULLIBLES_TRAVELS"=>285,
"EVEN_MORE_GULLIBLES_TRAVELS"=>286,
"HEIR_OF_THE_NEW_MOON"=>287,
"ASSASSIN_REJECT"=>288,
"BLACK_BELT"=>289,
"VERMILLION_VENTURER"=>290,
"CERULEAN_SOLDIER"=>291,
"EMERALD_EXTERMINATOR"=>292,
"GUIDING_STAR"=>293,
"VESTAL_CHAMBERLAIN"=>294,
"SAN_DORIAN_ROYAL_HEIR"=>295,
"HERO_AMONG_HEROES"=>296,
"DYNAMISSAN_DORIA_INTERLOPER"=>297,
"DYNAMISBASTOK_INTERLOPER"=>298,
"DYNAMISWINDURST_INTERLOPER"=>299,
"DYNAMISJEUNO_INTERLOPER"=>300,
"DYNAMISBEAUCEDINE_INTERLOPER"=>301,
"DYNAMISXARCABARD_INTERLOPER"=>302,
"DISCERNING_INDIVIDUAL"=>303,
"VERY_DISCERNING_INDIVIDUAL"=>304,
"EXTREMELY_DISCERNING_INDIVIDUAL"=>305,
"ROYAL_WEDDING_PLANNER"=>306,
"CONSORT_CANDIDATE"=>307,
"OBSIDIAN_STORM"=>308,
"PENTACIDE_PERPETRATOR"=>309,
"WOOD_WORSHIPER"=>310,
"LUMBER_LATHER"=>311,
"ACCOMPLISHED_CARPENTER"=>312,
"ANVIL_ADVOCATE"=>313,
"FORGE_FANATIC"=>314,
"ACCOMPLISHED_BLACKSMITH"=>315,
"TRINKET_TURNER"=>316,
"SILVER_SMELTER"=>317,
"ACCOMPLISHED_GOLDSMITH"=>318,
"KNITTING_KNOWITALL"=>319,
"LOOM_LUNATIC"=>320,
"ACCOMPLISHED_WEAVER"=>321,
"FORMULA_FIDDLER"=>322,
"POTION_POTENTATE"=>323,
"ACCOMPLISHED_ALCHEMIST"=>324,
"BONE_BEAUTIFIER"=>325,
"SHELL_SCRIMSHANDER"=>326,
"ACCOMPLISHED_BONEWORKER"=>327,
"HIDE_HANDLER"=>328,
"LEATHER_LAUDER"=>329,
"ACCOMPLISHED_TANNER"=>330,
"FASTRIVER_FISHER"=>331,
"COASTLINE_CASTER"=>332,
"ACCOMPLISHED_ANGLER"=>333,
"GOURMAND_GRATIFIER"=>334,
"BANQUET_BESTOWER"=>335,
"ACCOMPLISHED_CHEF"=>336,
"FINE_TUNER"=>337,
"FRIEND_OF_THE_HELMED"=>338,
"TAVNAZIAN_SQUIRE"=>339,
"DUCAL_DUPE"=>340,
"HYPER_ULTRA_SONIC_ADVENTURER"=>341,
"ROD_RETRIEVER"=>342,
"DEED_VERIFIER"=>343,
"CHOCOBO_LOVE_GURU"=>344,
"PICKUP_ARTIST"=>345,
"TRASH_COLLECTOR"=>346,
"ANCIENT_FLAME_FOLLOWER"=>347,
"TAVNAZIAN_TRAVELER"=>348,
"TRANSIENT_DREAMER"=>349,
"THE_LOST_ONE"=>350,
"TREADER_OF_AN_ICY_PAST"=>351,
"BRANDED_BY_LIGHTNING"=>352,
"SEEKER_OF_THE_LIGHT"=>353,
"DEAD_BODY"=>354,
"FROZEN_DEAD_BODY"=>355,
"DREAMBREAKER"=>356,
"MIST_MELTER"=>357,
"DELTA_ENFORCER"=>358,
"OMEGA_OSTRACIZER"=>359,
"ULTIMA_UNDERTAKER"=>360,
"ULMIAS_SOULMATE"=>361,
"TENZENS_ALLY"=>362,
"COMPANION_OF_LOUVERANCE"=>363,
"TRUE_COMPANION_OF_LOUVERANCE"=>364,
"PRISHES_BUDDY"=>365,
"NAGMOLADAS_UNDERLING"=>366,
"ESHANTARLS_COMRADE_IN_ARMS"=>367,
"THE_CHEBUKKIS_WORST_NIGHTMARE"=>368,
"BROWN_MAGE_GUINEA_PIG"=>369,
"BROWN_MAGIC_BYPRODUCT"=>370,
"BASTOKS_SECOND_BEST_DRESSED"=>371,
"ROOKIE_HERO_INSTRUCTOR"=>372,
"GOBLIN_IN_DISGUISE"=>373,
"APOSTATE_FOR_HIRE"=>374,
"TALKS_WITH_TONBERRIES"=>375,
"ROOK_BUSTER"=>376,
"BANNERET"=>377,
"GOLD_BALLI_STAR"=>378,
"MYTHRIL_BALLI_STAR"=>379,
"SILVER_BALLI_STAR"=>380,
"BRONZE_BALLI_STAR"=>381,
"SEARING_STAR"=>382,
"STRIKING_STAR"=>383,
"SOOTHING_STAR"=>384,
"SABLE_STAR"=>385,
"SCARLET_STAR"=>386,
"SONIC_STAR"=>387,
"SAINTLY_STAR"=>388,
"SHADOWY_STAR"=>389,
"SAVAGE_STAR"=>390,
"SINGING_STAR"=>391,
"SNIPING_STAR"=>392,
"SLICING_STAR"=>393,
"SNEAKING_STAR"=>394,
"SPEARING_STAR"=>395,
"SUMMONING_STAR"=>396,
"PUTRID_PURVEYOR_OF_PUNGENT_PETALS"=>397,
"UNQUENCHABLE_LIGHT"=>398,
"BALLISTAGER"=>399,
"ULTIMATE_CHAMPION_OF_THE_WORLD"=>400,
"WARRIOR_OF_THE_CRYSTAL"=>401,
"INDOMITABLE_FISHER"=>402,
"AVERTER_OF_THE_APOCALYPSE"=>403,
"BANISHER_OF_EMPTINESS"=>404,
"RANDOM_ADVENTURER"=>405,
"IRRESPONSIBLE_ADVENTURER"=>406,
"ODOROUS_ADVENTURER"=>407,
"INSIGNIFICANT_ADVENTURER"=>408,
"FINAL_BALLI_STAR"=>409,
"BALLI_STAR_ROYALE"=>410,
"DESTINED_FELLOW"=>411,
"ORCISH_SERJEANT"=>412,
"BRONZE_QUADAV"=>413,
"YAGUDO_INITIATE"=>414,
"MOBLIN_KINSMAN"=>415,
"SIN_HUNTER_HUNTER"=>416,
"DISCIPLE_OF_JUSTICE"=>417,
"MONARCH_LINN_PATROL_GUARD"=>418,
"TEAM_PLAYER"=>419,
"WORTHY_OF_TRUST"=>420,
"CONQUEROR_OF_FATE"=>421,
"BREAKER_OF_THE_CHAINS"=>422,
"A_FRIEND_INDEED"=>423,
"HEIR_TO_THE_REALM_OF_DREAMS"=>424,
"GOLD_HOOK"=>425,
"MYTHRIL_HOOK"=>426,
"SILVER_HOOK"=>427,
"COPPER_HOOK"=>428,
"--Unused"=>429,
"DYNAMISVALKURM_INTERLOPER"=>430,
"DYNAMISBUBURIMU_INTERLOPER"=>431,
"DYNAMISQUFIM_INTERLOPER"=>432,
"DYNAMISTAVNAZIA_INTERLOPER"=>433,
"CONFRONTER_OF_NIGHTMARES"=>434,
"DISTURBER_OF_SLUMBER"=>435,
"INTERRUPTER_OF_DREAMS"=>436,
"SAPPHIRE_STAR"=>437,
"SURGING_STAR"=>438,
"SWAYING_STAR"=>439,
"DARK_RESISTANT"=>440,
"BEARER_OF_THE_MARK_OF_ZAHAK"=>441,
"SEAGULL_PHRATRIE_CREW_MEMBER"=>442,
"PROUD_AUTOMATON_OWNER"=>443,
"PRIVATE_SECOND_CLASS"=>444,
"PRIVATE_FIRST_CLASS"=>445,
"SUPERIOR_PRIVATE"=>446,
"WILDCAT_PUBLICIST"=>447,
"ADAMANTKING_USURPER"=>448,
"OVERLORD_OVERTHROWER"=>449,
"DEITY_DEBUNKER"=>450,
"FAFNIR_SLAYER"=>451,
"ASPIDOCHELONE_SINKER"=>452,
"NIDHOGG_SLAYER"=>453,
"MAAT_MASHER"=>454,
"KIRIN_CAPTIVATOR"=>455,
"CACTROT_DESACELERADOR"=>456,
"LIFTER_OF_SHADOWS"=>457,
"TIAMAT_TROUNCER"=>458,
"VRTRA_VANQUISHER"=>459,
"WORLD_SERPENT_SLAYER"=>460,
"XOLOTL_XTRAPOLATOR"=>461,
"BOROKA_BELEAGUERER"=>462,
"OURYU_OVERWHELMER"=>463,
"VINEGAR_EVAPORATOR"=>464,
"VIRTUOUS_SAINT"=>465,
"BYEBYE_TAISAI"=>466,
"TEMENOS_LIBERATOR"=>467,
"APOLLYON_RAVAGER"=>468,
"WYRM_ASTONISHER"=>469,
"NIGHTMARE_AWAKENER"=>470,
"CERBERUS_MUZZLER"=>471,
"HYDRA_HEADHUNTER"=>472,
"SHINING_SCALE_RIFLER"=>473,
"TROLL_SUBJUGATOR"=>474,
"GORGONSTONE_SUNDERER"=>475,
"KHIMAIRA_CARVER"=>476,
"ELITE_EINHERJAR"=>477,
"STAR_CHARIOTEER"=>478,
"SUN_CHARIOTEER"=>479,
"SUBDUER_OF_THE_MAMOOL_JA"=>480,
"SUBDUER_OF_THE_TROLLS"=>481,
"SUBDUER_OF_THE_UNDEAD_SWARM"=>482,
"AGENT_OF_THE_ALLIED_FORCES"=>483,
"SCENIC_SNAPSHOTTER"=>484,
"BRANDED_BY_THE_FIVE_SERPENTS"=>485,
"IMMORTAL_LION"=>486,
"PARAGON_OF_BLUE_MAGE_EXCELLENCE"=>487,
"PARAGON_OF_CORSAIR_EXCELLENCE"=>488,
"PARAGON_OF_PUPPETMASTER_EXCELLENCE"=>489,
"LANCE_CORPORAL"=>490,
"CORPORAL"=>491,
"MASTER_OF_AMBITION"=>492,
"MASTER_OF_CHANCE"=>493,
"MASTER_OF_MANIPULATION"=>494,
"OVJANGS_ERRAND_RUNNER"=>495,
"SERGEANT"=>496,
"SERGEANT_MAJOR"=>497,
"KARABABAS_TOUR_GUIDE"=>498,
"KARABABAS_BODYGUARD"=>499,
"KARABABAS_SECRET_AGENT"=>500,
"SKYSERPENT_AGGRANDIZER"=>501,
"CHIEF_SERGEANT"=>502,
"APHMAUS_MERCENARY"=>503,
"NASHMEIRAS_MERCENARY"=>504,
"CHOCOROOKIE"=>505,
"SECOND_LIEUTENANT"=>506,
"GALESERPENT_GUARDIAN"=>507,
"STONESERPENT_SHOCKTROOPER"=>508,
"PHOTOPTICATOR_OPERATOR"=>509,
"SALAHEEMS_RISK_ASSESSOR"=>510,
"TREASURE_TROVE_TENDER"=>511,
"GESSHOS_MERCY"=>512,
"EMISSARY_OF_THE_EMPRESS"=>513,
"ENDYMION_PARATROOPER"=>514,
"NAJAS_COMRADEINARMS"=>515,
"NASHMEIRAS_LOYALIST"=>516,
"PREVENTER_OF_RAGNAROK"=>517,
"CHAMPION_OF_AHT_URHGAN"=>518,
"FIRST_LIEUTENANT"=>519,
"CAPTAIN"=>520,
"CRYSTAL_STAKES_CUPHOLDER"=>521,
"WINNING_OWNER"=>522,
"VICTORIOUS_OWNER"=>523,
"TRIUMPHANT_OWNER"=>524,
"HIGH_ROLLER"=>525,
"FORTUNES_FAVORITE"=>526,
"SUPERHERO"=>527,
"SUPERHEROINE"=>528,
"BLOODY_BERSERKER"=>529,
"THE_SIXTH_SERPENT"=>530,
"ETERNAL_MERCENARY"=>531,
"SPRINGSERPENT_SENTRY"=>532,
"SPRIGHTLY_STAR"=>533,
"SAGACIOUS_STAR"=>534,
"SCHULTZ_SCHOLAR"=>535,
"KNIGHT_OF_THE_IRON_RAM"=>536,
"FOURTH_DIVISION_SOLDIER"=>537,
"COBRA_UNIT_MERCENARY"=>538,
"WINDTALKER"=>539,
"LADY_KILLER"=>540,
"TROUPE_BRILIOTH_DANCER"=>541,
"CAIT_SITHS_ASSISTANT"=>542,
"AJIDOMARUJIDOS_MINDER"=>543,
"COMET_CHARIOTEER"=>544,
"MOON_CHARIOTEER"=>545,
"SANDWORM_WRANGLER"=>546,
"IXION_HORNBREAKER"=>547,
"LAMBTON_WORM_DESEGMENTER"=>548,
"PANDEMONIUM_QUELLER"=>549,
"DEBASER_OF_DYNASTIES"=>550,
"DISPERSER_OF_DARKNESS"=>551,
"ENDER_OF_IDOLATRY"=>552,
"LUGH_EXORCIST"=>553,
"ELATHA_EXORCIST"=>554,
"ETHNIU_EXORCIST"=>555,
"TETHRA_EXORCIST"=>556,
"BUARAINECH_EXORCIST"=>557,
"OUPIRE_IMPALER"=>558,
"SCYLLA_SKINNER"=>559,
"ZIRNITRA_WINGCLIPPER"=>560,
"DAWON_TRAPPER"=>561,
"KRABKATOA_STEAMER"=>562,
"ORCUS_TROPHY_HUNTER"=>563,
"BLOBDINGNAG_BURSTER"=>564,
"VERTHANDI_ENSNARER"=>565,
"RUTHVEN_ENTOMBER"=>566,
"YILBEGAN_HIDEFLAYER"=>567,
"TORCHBEARER_OF_THE_1ST_WALK"=>568,
"TORCHBEARER_OF_THE_2ND_WALK"=>569,
"TORCHBEARER_OF_THE_3RD_WALK"=>570,
"TORCHBEARER_OF_THE_4TH_WALK"=>571,
"TORCHBEARER_OF_THE_5TH_WALK"=>572,
"TORCHBEARER_OF_THE_6TH_WALK"=>573,
"TORCHBEARER_OF_THE_7TH_WALK"=>574,
"TORCHBEARER_OF_THE_8TH_WALK"=>575,
"FURNITURE_STORE_OWNER"=>576,
"ARMORY_OWNER"=>577,
"JEWELRY_STORE_OWNER"=>578,
"BOUTIQUE_OWNER"=>579,
"APOTHECARY_OWNER"=>580,
"CURIOSITY_SHOP_OWNER"=>581,
"SHOESHOP_OWNER"=>582,
"FISHMONGER_OWNER"=>583,
"RESTAURANT_OWNER"=>584,
"ASSISTANT_DETECTIVE"=>585,
"PROMISING_DANCER"=>586,
"STARDUST_DANCER"=>587,
"ELEGANT_DANCER"=>588,
"DAZZLING_DANCE_DIVA"=>589,
"FRIEND_OF_LEHKO_HABHOKA"=>590,
"SUMMA_CUM_LAUDE"=>591,
"GRIMOIRE_BEARER"=>592,
"SEASONING_CONNOISSEUR"=>593,
"FINE_YOUNG_GRIFFON"=>594,
"BABBANS_TRAVELING_COMPANION"=>595,
"FELLOW_FORTIFIER"=>596,
"CHOCOCHAMPION"=>597,
"TRAVERSER_OF_TIME"=>598,
"MYTHRIL_MUSKETEER_NO_6"=>599,
"JEWEL_OF_THE_COBRA_UNIT"=>600,
"KNIGHT_OF_THE_SWIFTWING_GRIFFIN"=>601,
"WYRMSWORN_PROTECTOR"=>602,
"FLAMESERPENT_FACILITATOR"=>603,
"MAZE_WANDERER"=>604,
"MAZE_NAVIGATOR"=>605,
"MAZE_SCHOLAR"=>606,
"MAZE_ARTISAN"=>607,
"MAZE_OVERLORD"=>608,
"SWARMINATOR"=>609,
"BATTLE_OF_JEUNO_VETERAN"=>610,
"GRAND_GREEDALOX"=>611,
"KARAHABARUHAS_RESEARCH_ASSISTANT"=>612,
"HONORARY_KNIGHT_OF_THE_CARDINAL_STAG"=>613,
"DETECTOR_OF_DECEPTION"=>614,
"SILENCER_OF_THE_ECHO"=>615,
"BESTRIDER_OF_FUTURES"=>616,
"MOG_HOUSE_HANDYPERSON"=>617,
"PRESIDENTIAL_PROTECTOR"=>618,
"THE_MOONS_COMPANION"=>619,
"ARRESTER_OF_THE_ASCENSION"=>620,
"HOUSE_AURCHIAT_RETAINER"=>621,
"WANDERER_OF_TIME"=>622,
"SMITER_OF_THE_SHADOW"=>623,
"HEIR_OF_THE_BLESSED_RADIANCE"=>624,
"HEIR_OF_THE_BLIGHTED_GLOOM"=>625,
"SWORN_TO_THE_DARK_DIVINITY"=>626,
"TEMPERER_OF_MYTHRIL"=>627,
"STAR_IN_THE_AZURE_SKY"=>628,
"FANGMONGER_FORESTALLER"=>629,
"VISITOR_TO_ABYSSEA"=>630,
"FRIEND_OF_ABYSSEA"=>631,
"WARRIOR_OF_ABYSSEA"=>632,
"STORMER_OF_ABYSSEA"=>633,
"DEVASTATOR_OF_ABYSSEA"=>634,
"HERO_OF_ABYSSEA"=>635,
"CHAMPION_OF_ABYSSEA"=>636,
"CONQUEROR_OF_ABYSSEA"=>637,
"SAVIOR_OF_ABYSSEA"=>638,
"VANQUISHER_OF_SPITE"=>639,
"HADHAYOSH_HALTERER"=>640,
"BRIAREUS_FELLER"=>641,
"KARKINOS_CLAWCRUSHER"=>642,
"CARABOSSE_QUASHER"=>643,
"OVNI_OBLITERATOR"=>644,
"RUMINATOR_CONFOUNDER"=>645,
"ECCENTRICITY_EXPUNGER"=>646,
"FISTULE_DRAINER"=>647,
"KUKULKAN_DEFANGER"=>648,
"TURUL_GROUNDER"=>649,
"BLOODEYE_BANISHER"=>650,
"SATIATOR_DEPRIVER"=>651,
"IRATHAM_CAPTURER"=>652,
"LACOVIE_CAPSIZER"=>653,
"CHLORIS_UPROOTER"=>654,
"MYRMECOLEON_TAMER"=>655,
"GLAVOID_STAMPEDER"=>656,
"USURPER_DEPOSER"=>657,
"YAANEI_CRASHER"=>658,
"KUTHAREI_UNHORSER"=>659,
"SIPPOY_CAPTURER"=>660,
"TITLACAUAN_DISMEMBERER"=>661,
"SMOK_DEFOGGER"=>662,
"AMHULUK_INUNDATER"=>663,
"PULVERIZER_DISMANTLER"=>664,
"DURINN_DECEIVER"=>665,
"KARKADANN_EXOCULATOR"=>666,
"ULHUADSHI_DESICCATOR"=>667,
"ITZPAPALOTL_DECLAWER"=>668,
"SOBEK_MUMMIFIER"=>669,
"CIREINCROIN_HARPOONER"=>670,
"BUKHIS_TETHERER"=>671,
"SEDNA_TUSKBREAKER"=>672,
"CLEAVER_DISMANTLER"=>673,
"EXECUTIONER_DISMANTLER"=>674,
"SEVERER_DISMANTLER"=>675,
"LUSCA_DEBUNKER"=>676,
"TRISTITIA_DELIVERER"=>677,
"KETEA_BEACHER"=>678,
"RANI_DECROWNER"=>679,
"ORTHRUS_DECAPITATOR"=>680,
"DRAGUA_SLAYER"=>681,
"BENNU_DEPLUMER"=>682,
"HEDJEDJET_DESTINGER"=>683,
"CUIJATENDER_DESICCATOR"=>684,
"BRULO_EXTINGUISHER"=>685,
"PANTOKRATOR_DISPROVER"=>686,
"APADEMAK_ANNIHILATOR"=>687,
"ISGEBIND_DEFROSTER"=>688,
"RESHEPH_ERADICATOR"=>689,
"EMPOUSA_EXPURGATOR"=>690,
"INDRIK_IMMOLATOR"=>691,
"OGOPOGO_OVERTURNER"=>692,
"RAJA_REGICIDE"=>693,
"ALFARD_DETOXIFIER"=>694,
"AZDAJA_ABOLISHER"=>695,
"AMPHITRITE_SHUCKER"=>696,
"FUATH_PURIFIER"=>697,
"KILLAKRIQ_EXCORIATOR"=>698,
"MAERE_BESTIRRER"=>699,
"WYRM_GOD_DEFIER"=>700,
"HAHAVA_CONDEMNER"=>701,
"CELAENO_SILENCER"=>702,
"VOIDWROUGHT_DECONSTRUCTOR"=>703,
"DEVOURER_OF_SHADOWS"=>704,
"KAGGEN_CLOBBERER"=>705,
"AKVAN_ABSTERGER"=>706,
"PIL_UNFROCKER"=>707,
"QILIN_CONTRAVENER"=>708,
"UPTALA_REPROBATOR"=>709,
"AELLO_ABATOR"=>710,
"TORCHBEARER_OF_THE_9TH_WALK"=>711,
"TORCHBEARER_OF_THE_10TH_WALK"=>712,
"TORCHBEARER_OF_THE_11TH_WALK"=>713,
"NIGHTMARE_ILLUMINATOR"=>714,
"GAUNAB_GUTTER"=>715,
"KALASUTRAX_CREMATOR"=>716,
"OCYTHOE_OVERRIDER"=>717,
"IG_ALIMA_INHUMER"=>718,
"BOTULUS_REX_ENGORGER"=>719,
"TORCHBEARER_OF_THE_12TH_WALK"=>720,
"TORCHBEARER_OF_THE_13TH_WALK"=>721,
"TORCHBEARER_OF_THE_14TH_WALK"=>722,
"TORCHBEARER_OF_THE_15TH_WALK"=>723,
"DELVER_OF_THE_DEPTHS"=>724,
"SUBJUGATOR_OF_THE_LOFTY"=>725,
"SUBJUGATOR_OF_THE_MIRED"=>726,
"SUBJUGATOR_OF_THE_SOARING"=>727,
"SUBJUGATOR_OF_THE_VEILED"=>728,
"LEGENDARY_LEGIONNAIRE"=>729,
"WITNESS_TO_PROVENANCE"=>730,
"BISMARCK_FLENSER"=>731,
"MORTA_EXTIRPATOR"=>732,
"UNSUNG_HEROINE"=>733,
"EPIC_HEROINE"=>734,
"EPIC_EINHERJAR"=>735,
"MENDER_OF_WINGS"=>736,
"CHAMPION_OF_THE_DAWN"=>737,
"BUSHIN_ASPIRANT"=>738,
"BUSHIN_RYU_INHERITOR"=>739,
"TEMENOS_EMANCIPATOR"=>740,
"APOLLYON_RAZER"=>741,
"GOLDWING_SQUASHER"=>742,
"SILAGILITH_DETONATOR"=>743,
"SURTR_SMOTHERER"=>744,
"DREYRUK_PREDOMINATOR"=>745,
"SAMURSK_VITIATOR"=>746,
"UMAGRHK_MANEMANGLER"=>747,
"SUPERNAL_SAVANT"=>748,
"SOLAR_SAGE"=>749,
"BOLIDE_BARON"=>750,
"MOON_MAVEN"=>751,
"IZYX_VEXER"=>752,
"GRANNUS_GARROTER"=>753,
"SVAHA_STRIKER"=>754,
"MELISSEUS_DOMESTICATOR"=>755,
"WATERWAY_EXEMPLAR"=>756,
"CAVERN_EXEMPLAR"=>757,
"MUYINGWA_WINGCRUSHER"=>758,
"DAKUWAQA_TRAWLER"=>759,
"TOJIL_DOUSER"=>760,
"COLKHAB_DETHRONER"=>761,
"ACHUKA_GLACIATOR"=>762,
"TCHAKKA_DESICCATOR"=>763,
"WEALD_EXEMPLAR"=>764,
"HURKAN_BIRDLIMEIST"=>765,
"YUMCAX_LOGGER"=>766,
"COLKHAB_HIVECRUSHER"=>767,
"ACHUKA_COAGULATOR"=>768,
"TCHAKKA_FILLETER"=>769,
"RABBIT_TUSSLER"=>770,
"HELMINTH_MINCER"=>771,
"MANDRAGARDENER"=>772,
"MOPPET_MASSACRER"=>773,
"RIP_ROARING_LIMBRENDER"=>774,
"SHELL_SHOCKER"=>775,
"YAGUDO_COOPKEEPER"=>776,
"GIGASPLOSION_EXPERT"=>777,
"BROTHER_IN_ARMS"=>778,
"ANTICA_HUNTER"=>779,
"AMPHIBIAN_ADULTERATOR"=>780,
"TONBERRY_TOPPLER"=>781,
"BLOODLINE_CORRUPTER"=>782,
"KUMHAU_ROASTER"=>783,
"BRILLIANCE_MANIFEST"=>784,
"QUIETER_OF_ANCIENT_THOUGHTS"=>785,
"ARK_HUME_HUMILIATOR"=>786,
"ARK_ELVAAN_EVISCERATOR"=>787,
"ARK_MITHRA_MALIGNER"=>788,
"ARK_TARUTARU_TROUNCER"=>789,
"ARK_GALKA_GOUGER"=>790,
"PENTARCH_PACIFIER"=>791,
"DREAM_DISTILLER"=>792,
"RAKAZNAR_EXEMPLAR"=>793,
"UTKUX_PELTBURNER"=>794,
"CAILIMH_PLUMAGEPLUCKER"=>795,
"WOPKET_TRUNKSPLITTER"=>796,
"OURYU_OBFUSCATOR"=>797,
"UNWAVERING_BLAZE"=>798,
"LANCELORD_DIVESTER"=>799,
"GESSHO_PINIONER"=>800,
"SIN_PURGER"=>801,
"ADUMBRATION_DISPERSER"=>802,
"QUELLER_OF_OTHERWORLDLY_GALES"=>803,
"BLAZE_MARSHALLER"=>804,
"PENITENTES_BLASTER"=>805,
"SIROCCO_TAMER"=>806,
"SUCHIAN_FELLER"=>807,
"OMBIFID_SLAYER"=>808,
"NILOTICAN_DECIMATOR"=>809,
"ILLUMINATOR_OF_THE_1ST_WALK"=>810,
"ILLUMINATOR_OF_THE_2ND_WALK"=>811,
"ILLUMINATOR_OF_THE_3RD_WALK"=>812,
"ILLUMINATOR_OF_THE_4TH_WALK"=>813,
"ILLUMINATOR_OF_THE_5TH_WALK"=>814,
"ILLUMINATOR_OF_THE_6TH_WALK"=>815,
"ILLUMINATOR_OF_THE_7TH_WALK"=>816,
"ILLUMINATOR_OF_THE_8TH_WALK"=>817,
"ILLUMINATOR_OF_THE_9TH_WALK"=>818,
"ILLUMINATOR_OF_THE_10TH_WALK"=>819,
"ILLUMINATOR_OF_THE_11TH_WALK"=>820,
"ILLUMINATOR_OF_THE_12TH_WALK"=>821,
"ILLUMINATOR_OF_THE_13TH_WALK"=>822,
"ILLUMINATOR_OF_THE_14TH_WALK"=>823,
"ILLUMINATOR_OF_THE_15TH_WALK"=>824,
"LITHOSPHERE_ANNIHILATOR"=>825,
"FULMINATION_DISRUPTOR"=>826,
"BORE_REPULSOR"=>827,
"--Unused"=>828,
"--Unused"=>829,
"--Unused"=>830,
"--Unused"=>831,
"--Unused"=>832,
"--Unused"=>833,
"--Unused"=>834,
"--Unused"=>835,
"GEODANCER"=>836,
"RUNIC_ENGRAVER"=>837,
"APPRENTICE_TARUTARU_SAUCE_MANAGER"=>838,
"VEGETABLE_REVOLUTIONARY"=>839,
"FRIEND_TO_GLUTTONS"=>840,
"WAYPOINT_WARRIOR"=>841,
"ULBUKAN_STALWART"=>842,
"TOXIN_TUSSLER"=>843,
"SPIRITUAL_STAR"=>844,
"STIPPLING_STAR"=>845,
"GEOMANCIPATOR"=>846,
"TRIALED_AND_TRUE_RUNEIST"=>847,
"QUEENS_CONFIDANTE"=>848,
"PRINCESSS_PARTISAN"=>849,
"POTATION_PATHFINDER"=>850,
"STORIED_GEOMANCER"=>851,
"ULTIMATE_RUNEIST"=>852,
"MOG_GARDEN_SEEDLING"=>853,
"KIT_EMPATHIZER"=>854,
"JINGLY_DANGLER"=>855,
"MOLE_MANIPULATOR"=>856,
"AGRARIAN_NOVICE"=>857,
"AGRARIAN_INITIATE"=>858,
"AGRARIAN_PROFESSIONAL"=>859,
"AGRARIAN_VIRTUOSO"=>860,
"AGRARIAN_TUTELAR"=>861,
"WEED_PRAETOR"=>862,
"TREE_PRAETOR"=>863,
"THICKET_PRAETOR"=>864,
"FOREST_PRAETOR"=>865,
"JUNGLE_PRAETOR"=>866,
"COPPER_MATTOCK"=>867,
"SILVER_MATTOCK"=>868,
"MYTHRIL_MATTOCK"=>869,
"GOLD_MATTOCK"=>870,
"ADAMANTTOCK"=>871,
"PUDDLE_PATRON"=>872,
"SWAMP_SAVANT"=>873,
"POND_PRECEPTOR"=>874,
"RIVER_REGENT"=>875,
"MONKE_ONKE_MASTER"=>876,
"SARDINEOPHYTE"=>877,
"CALAMAREELER"=>878,
"OCTOPOTENTATE"=>879,
"GIANT_SQUIMPERATOR"=>880,
"LEVIAUTHORITY"=>881,
"NOVICE_NURSERYMAN"=>882,
"LESSER_LANDSCAPER"=>883,
"GREATER_GARDENER"=>884,
"HONORED_HORTICULTURIST"=>885,
"MOG_GARDENER"=>886,
"BRYGIDESQUE_MANAGER"=>887,
"VEGETABLE_EVOLUTIONARY"=>888,
"BLADE_ENTHUSIAST"=>889,
"RUNIC_EMISSARY"=>890,
"MAESTER_OF_MADDENING"=>891,
"SUNSHINE_CADET"=>892,
"QUARTET_CAPTIVATOR"=>893,
"THE_TRUSTWORTHY"=>894,
"THE_LOVELORN"=>895,
"INVENTOR_EXTRAORDINAIRE"=>896,
"BOOMY_AND_BUSTY"=>897,
"WEATHERER_OF_BRUMAL_CLIMES"=>898,
"WHITE_KNIGHT"=>899,
"LIGHT_OF_DAWN"=>900,
"OBSERVER_OF_FATEFUL_CUBES"=>901,
"KNOWER_OF_UNTRUTHS"=>902,
"ULBUKAN_UNDERSTUDY"=>903,
"KEEPER_OF_ULBUKA"=>904,
"RADIANCE_OF_DAYBREAK"=>905,
"WIBBLY_WOBBLY_WOOZY_WARRIOR"=>906,
"HEIR_OF_ETERNITY"=>907,
"PROSPECTIVE_PAMPERER"=>908,
"NOVICE_NUZZLER"=>909,
"SERIOUS_SNUGGLER"=>910,
"CULTIVATED_CODDLER"=>911,
"RESPECTED_RUFFLER"=>912,
"DUNG_DISSEMINATOR"=>913,
"FAUNA_FEEDER"=>914,
"CONFIDENT_CARETAKER"=>915,
"GLORIOUS_GROOMER"=>916,
"TRANSCENDENTAL_TAMER"=>917,
"BOND_BUILDING_BREEDER"=>918,
"CLUMSY_CLEAVER"=>919,
"DISCIPLINED_DISSECTOR"=>920,
"ESTABLISHED_EXAMINER"=>921,
"SUBLIME_SLICER"=>922,
"LIFTER_OF_SPIRITS"=>923,
"SHEDDER_OF_HARLEQUIN_TEARS"=>924,
"HOPE_FOR_THE_FUTURE"=>925,
"THOUSAND_YEAR_TRAVELER"=>926,
"VANQUISHER_OF_ASHRAKK"=>927,
"VANQUISHER_OF_DHOKMAK"=>928,
"PROTECTED_BY_ULBUKAN_SPIRITS"=>929,
"RECEIVER_OF_SIGILS"=>930,
"DESTROYER_OF_HADES"=>931,
"BRINGER_OF_THE_DAWN"=>932,
"THE_ONE_TRUE_PIONEER"=>933,
"BRINGER_OF_HOPE"=>934,

);

$real_title = array_flip($titles);

	$slot_array = array(
		1=>"Main",
		2=>"Sub",
		3=>"Main, Sub",
		4=>"Ranged",
		8=>"Ammo",
		16=>"Head",
		32=>"Body",
		64=>"Hands",
		128=>"Legs",
		256=>"Feet",
		512=>"Neck",
		1024=>"Waist",
		6144=>"Ears",
		24576=>"Rings",
		32768=>"Back"
		
);

$flag_array = array(
		0=>"None",
		1=>"Wall Hanging",
		16=>"Inner Delivery",
		32=>"Inscribable",
		64=>"No Auction",
		128=>"Scroll",
		256=>"Unknown",
		512=>"Can Use",
		1024=>"Can Trade NPC",
		2048=>"Can Equip",
		4096=>"No Sale",
		8192=>"No Delivery",
		16384=>"Ex",
		32768=>"Rare"
		
);

$jobs_array = array(

1=>"war",
2=>"mnk",
4=>"whm",
8=>"blm",
16=>"rdm",
32=>"thf",
64=>"pld",
128=>"drk",
256=>"bst",
512=>"brd",
1024=>"rng",
2048=>"sam",
4096=>"nin",
8192=>"drg",
16384=>"smn",
32768=>"blu",
65536=>"cor",
131072=>"pup",
262144=>"dnc",
524288=>"sch",
1048576=>"geo",
2097152=>"run"
);



$skills = array(
		0=>"N/A",
		1=>"Hand-to-Hand",
		2=>"Dagger",
		3=>"Sword",
		4=>"Great Sword",
		5=>"Axe",
		6=>"Great Axe",
		7=>"Scythe",
		8=>"Polearm",
		9=>"Katana",
		10=>"Great Katana",
		11=>"Club",
		12=>"Staff",
		25=>"Archery",
		26=>"Marksmanship",
		27=>"Throwing"
);

	$damage = array(
		0=>"None",
		1=>"Piercing",
		2=>"Slashing",
		3=>"Blunt",
		4=>"Hand-to-Hand",
		5=>"Crossbow",
		6=>"Gun"
);


$ahcat= array(
0=>"N/A",
1=>"Hand-to-Hand",
2=>"Daggers",
3=>"Swords",
4=>"Great Swords",
5=>"Axes",
6=>"Great Axes",
7=>"Scythes",
8=>"Polearms",
9=>"Katana",
10=>"Great Katana",
11=>"Clubs",
12=>"Staves",
13=>"Ranged",
14=>"Instruments",
15=>"Ammunition",
16=>"Shields",
17=>"Helms",
18=>"Body",
19=>"Gloves",
20=>"Legs",
21=>"Feet",
22=>"Neck",
23=>"Waist",
24=>"Earrings",
25=>"Rings",
26=>"Back",
28=>"White Magic",
29=>"Black Magic",
30=>"Summoning",
31=>"Ninjutsu",
32=>"Songs",
33=>"Medicines",
34=>"Furnishings",
35=>"Crystals",
36=>"Cards",
37=>"Cursed Items",
38=>"Smithing",
39=>"Goldsmithing",
40=>"Clothcraft",
41=>"Leathercraft",
42=>"Bonecraft",
43=>"Woodworking",
44=>"Alchemy",
46=>"Misc.",
47=>"Fishing Gear",
48=>"Pet Items",
49=>"Ninja Tools",
50=>"Beast-made",
51=>"Fish",
52=>"Meat & Eggs",
53=>"Seafood",
54=>"Vegetables",
55=>"Soups",
56=>"Bread & Rice",
57=>"Sweets",
58=>"Drinks",
59=>"Ingredients",
60=>"Dice",
61=>"Automation",
62=>"Grips"
);

$latent = array(
"LATENT_HP_UNDER_PERCENT"=>0,//hplessthanorequalto%-PARAM:HPPERCENT
"LATENT_HP_OVER_PERCENT"=>1,//hpmorethan%-PARAM:HPPERCENT
"LATENT_HP_UNDER_TP_UNDER_100"=>2,//hplessthanorequalto%,tpunder100-PARAM:HPPERCENT
"LATENT_HP_OVER_TP_UNDER_100"=>3,//hpmorethan%,tpover100-PARAM:HPPERCENT
"LATENT_HP_OVER_VISIBLE_GEAR"=>46,//hpmorethanorequalto%,calculatedusingHPbonusesfromvisiblegearonly
"LATENT_MP_UNDER_PERCENT"=>4,//mplessthanorequalto%-PARAM:MPPERCENT
"LATENT_MP_UNDER"=>5,//mplessthan#-PARAM:MP#
"LATENT_MP_UNDER_VISIBLE_GEAR"=>45,//mplessthanorequalto%,calculatedusingMPbonusesfromvisiblegearonly
"LATENT_TP_UNDER"=>6,//tpunder#andduringWS-PARAM:TPVALUE
"LATENT_TP_OVER"=>7,//tpover#-PARAM:TPVALUE
"LATENT_SUBJOB"=>8,//subjob-PARAM:JOBTYPE
"LATENT_PET_ID"=>9,//pettype-PARAM:PETID
"LATENT_WEAPON_DRAWN"=>10,//weapondrawn
"LATENT_WEAPON_SHEATHED"=>11,//weaponsheathed
"LATENT_STATUS_EFFECT_ACTIVE"=>13,//statuseffectonplayer-PARAM:EFFECTID
"LATENT_FOOD_ACTIVE"=>49,//foodeffect(foodId)active-PARAM:FOODITEMID
"LATENT_NO_FOOD_ACTIVE"=>14,//nofoodeffectsactiveonplayer
"LATENT_PARTY_MEMBERS"=>15,//partysize#-PARAM:#OFMEMBERS
"LATENT_PARTY_MEMBERS_IN_ZONE"=>16,//partysize#andmembersinzone-PARAM:#OFMEMBERS
"LATENT_AVATAR_IN_PARTY"=>21,//partyhasaspecificavatar-PARAM:sameasglobals/pets.lua(21foranyavatar)
"LATENT_JOB_IN_PARTY"=>22,//partyhasjob-PARAM:JOBTYPE
"LATENT_ZONE"=>23,//inzone-PARAM:zoneid
"LATENT_SYNTH_TRAINEE"=>24,//synthskillunder40+nosupport
"LATENT_SONG_ROLL_ACTIVE"=>25,//anysongorrollactive
"LATENT_TIME_OF_DAY"=>26,//PARAM:0:DAYTIME1:NIGHTTIME2:DUSK-DAWN
"LATENT_HOUR_OF_DAY"=>27,//PARAM:1:NEWDAY,2:DAWN,3:DAY,4:DUSK,5:EVENING,6:DEADOFNIGHT
"LATENT_FIRESDAY"=>28,
"LATENT_EARTHSDAY"=>29,
"LATENT_WATERSDAY"=>30,
"LATENT_WINDSDAY"=>31,
"LATENT_DARKSDAY"=>32,
"LATENT_ICEDAY"=>34,
"LATENT_LIGHTNINGSDAY"=>35,
"LATENT_LIGHTSDAY"=>36,
"LATENT_MOON_FIRST_QUARTER"=>37,
"LATENT_JOB_MULTIPLE_5"=>38,
"LATENT_JOB_MULTIPLE_10"=>39,
"LATENT_JOB_MULTIPLE_13_NIGHT"=>40,
"LATENT_JOB_LEVEL_ODD"=>41,
"LATENT_JOB_LEVEL_EVEN"=>42,
"LATENT_WEAPON_DRAWN_HP_UNDER"=>43,//PARAM:HPPERCENT
"LATENT_WEAPON_BROKEN"=>47,
"LATENT_IN_DYNAMIS"=>48,
"LATENT_JOB_LEVEL_BELOW"=>50,//PARAM:level
"LATENT_JOB_LEVEL_ABOVE"=>51,//PARAM:level
"LATENT_WEATHER_ELEMENT"=>52,//PARAM:0:NONE,1:FIRE,2:EARTH,3:WATER,4:WIND,5:ICE,6:THUNDER,7:LIGHT,8:DARK
"LATENT_NATION_CONTROL"=>53,//checksifplayerregionisundernation'scontrol-PARAM:0:Underownnation'scontrol,1:Outsideownnation'scontrol
"LATENT_ZONE_HOME_NATION"=>54//inzoneandcitizenofnation(aketons)
);
$latent_name=array_flip($latent);

$mods = array(
"MOD_NONE"=>0x00,
"MOD_DEF"=>0x01,//Target'sDefense(modId"=>1)
"MOD_HP"=>0x02,//Target'sHP(modId"=>2)
"MOD_HPP"=>0x03,//HPPercentage(modId"=>3)
"MOD_CONVMPTOHP"=>0x04,//MP->HP(CassieEarring)(modId"=>4)
"MOD_MP"=>0x05,//MP+/-(modId"=>5)
"MOD_MPP"=>0x06,//MPPercentage(modId"=>6)
"MOD_CONVHPTOMP"=>0x07,//HP->MP(modId"=>7)
"MOD_STR"=>0x08,//Strength(modId"=>8)
"MOD_DEX"=>0x09,//Dexterity(modId"=>9)
"MOD_VIT"=>0x0A,//Vitality(modId"=>10)
"MOD_AGI"=>0x0B,//Agility(modId"=>11)
"MOD_INT"=>0x0C,//Intelligence(modId"=>12)
"MOD_MND"=>0x0D,//Mind(modId"=>13)
"MOD_CHR"=>0x0E,//Charisma(modId"=>14)
//ElementalDefenses
"MOD_FIREDEF"=>0x0F,//FireDefense(modId"=>15)
"MOD_ICEDEF"=>0x10,//IceDefense(modId"=>16)
"MOD_WINDDEF"=>0x11,//WindDefense(modId"=>17)
"MOD_EARTHDEF"=>0x12,//EarthDefense(modId"=>18)
"MOD_THUNDERDEF"=>0x13,//ThunderDefense(modId"=>19)
"MOD_WATERDEF"=>0x14,//WaterDefense(modId"=>20)
"MOD_LIGHTDEF"=>0x15,//LightDefense(modId"=>21)
"MOD_DARKDEF"=>0x16,//DarkDefense(modId"=>22)
"MOD_ATT"=>0x17,//Attack(modId"=>23)
"MOD_RATT"=>0x18,//RangedAttack(modId"=>24)
"MOD_ACC"=>0x19,//Accuracy(modId"=>25)
"MOD_RACC"=>0x1A,//RangedAccuracy(modId"=>26)
"MOD_ENMITY"=>0x1B,//Enmity(modId"=>27)
"MOD_ENMITY_LOSS_REDUCTION"=>0x1F6,//ReducesEnmitylostwhentakingdamage
"MOD_MATT"=>0x1C,//MagicAttack(modId"=>28)
"MOD_MDEF"=>0x1D,//MagicDefense(modId"=>29)
"MOD_MACC"=>0x1E,//MagicAccuracy(modId"=>30)
"MOD_MEVA"=>0x1F,//MagicEvasion(modId"=>31)
//MagicAccuracyandElementalAttacks
"MOD_FIREATT"=>0x20,//FireDamage(modId"=>32)
"MOD_ICEATT"=>0x21,//IceDamage(modId"=>33)
"MOD_WINDATT"=>0x22,//WindDamage(modId"=>34)
"MOD_EARTHATT"=>0x23,//EarthDamage(modId"=>35)
"MOD_THUNDERATT"=>0x24,//ThunderDamage(modId"=>36)
"MOD_WATERATT"=>0x25,//WaterDamage(modId"=>37)
"MOD_LIGHTATT"=>0x26,//LightDamage(modId"=>38)
"MOD_DARKATT"=>0x27,//DarkDamage(modId"=>39)
"MOD_FIREACC"=>0x28,//FireAccuracy(modId"=>40)
"MOD_ICEACC"=>0x29,//IceAccuracy(modId"=>41)
"MOD_WINDACC"=>0x2A,//WindAccuracy(modId"=>42)
"MOD_EARTHACC"=>0x2B,//EarthAccuracy(modId"=>43)
"MOD_THUNDERACC"=>0x2C,//ThunderAccuracy(modId"=>44)
"MOD_WATERACC"=>0x2D,//WaterAccuracy(modId"=>45)
"MOD_LIGHTACC"=>0x2E,//LightAccuracy(modId"=>46)
"MOD_DARKACC"=>0x2F,//DarkAccuracy(modId"=>47)
"MOD_WSACC"=>0x30,//WeaponskillAccuracy(modId"=>48)
//Resistancetodamagetype
//Valueisstoredasapercentageofdamagereduction(towithin1000)
//Example:1000"=>100%,875"=>87.5%
"MOD_SLASHRES"=>0x31,//SlashResistance(modId"=>49)
"MOD_PIERCERES"=>0x32,//PiercingResistance(modId"=>50)
"MOD_IMPACTRES"=>0x33,//ImpactResistance(modId"=>51)
"MOD_HTHRES"=>0x34,//Hand-To-HandResistance(modId"=>52)
//DamageReductiontoElements
//Valueisstoredasapercentageofdamagereduction(towithin1000)
//Example:1000"=>100%,875"=>87.5%
"MOD_FIRERES"=>0x36,//%FireResistance(modId"=>54)
"MOD_ICERES"=>0x37,//%IceResistance(modId"=>55)
"MOD_WINDRES"=>0x38,//%WindResistance(modId"=>56)
"MOD_EARTHRES"=>0x39,//%EarthResistance(modId"=>57)
"MOD_THUNDERRES"=>0x3A,//%ThunderResistance(modId"=>58)
"MOD_WATERRES"=>0x3B,//%WaterResistance(modId"=>59)
"MOD_LIGHTRES"=>0x3C,//%LightResistance(modId"=>60)
"MOD_DARKRES"=>0x3D,//%DarkResistance(modId"=>61)
"MOD_ATTP"=>0x3E,//%Attack(modId"=>62)
"MOD_DEFP"=>0x3F,//%Defense(modId"=>63)
"MOD_ACCP"=>0x40,//%Accuracy(modId"=>64)
"MOD_EVAP"=>0x41,//%Evasion(modId"=>65)
"MOD_RATTP"=>0x42,//%RangedAttack(modId"=>66)
"MOD_RACCP"=>0x43,//%RangedAttackAccuracy(modId"=>67)
"MOD_EVA"=>0x44,//Evasion(modId"=>68)
"MOD_RDEF"=>0x45,//RangedDefense(modId"=>69)
"MOD_REVA"=>0x46,//RangedEvasion(modId"=>70)
"MOD_MPHEAL"=>0x47,//MPRecoveredwhilehealing(modId"=>71)
"MOD_HPHEAL"=>0x48,//HPRecoveredwhilehealing(modId"=>72)
"MOD_STORETP"=>0x49,//IncreasestherateatwhichTPisgained(modId"=>73)
"MOD_TACTICAL_PARRY"=>0x1E6,//TacticalParryTpBonus(modId"=>486)
"MOD_MAG_BURST_BONUS"=>0x1E7,//MagicBurstBonusModifier(percent)(modId"=>487)
"MOD_INHIBIT_TP"=>0x1E8,//InhibitsTPGain(percent)(modId"=>488)
//WorkingSkills(weaponcombatskills)
"MOD_HTH"=>0x50,//HandToHandSkill(modId"=>80)
"MOD_DAGGER"=>0x51,//DaggerSkill(modId"=>81)
"MOD_SWORD"=>0x52,//SwordSkill(modId"=>82)
"MOD_GSWORD"=>0x53,//GreatSwordSkill(modId"=>83)
"MOD_AXE"=>0x54,//AxeSkill(modId"=>84)
"MOD_GAXE"=>0x55,//GreatAxeSkill(modId"=>85)
"MOD_SCYTHE"=>0x56,//ScytheSkill(modId"=>86)
"MOD_POLEARM"=>0x57,//PolearmSkill(modId"=>87)
"MOD_KATANA"=>0x58,//KatanaSkill(modId"=>88)
"MOD_GKATANA"=>0x59,//GreatKatanaSkill(modId"=>89)
"MOD_CLUB"=>0x5A,//ClubSkill(modId"=>90)
"MOD_STAFF"=>0x5B,//StaffSkill(modId"=>91)
"MOD_AUTO_MELEE_SKILL"=>0x65,//AutomatonMeleeSkill(modId"=>101)
"MOD_AUTO_RANGED_SKILL"=>0x66,//AutomatonRangeSkill(modId"=>102)
"MOD_AUTO_MAGIC_SKILL"=>0x67,//AutomatonMagicSkill(modId"=>103)
"MOD_ARCHERY"=>0x68,//ArcherySkill(modId"=>104)
"MOD_MARKSMAN"=>0x69,//MarksmanSkill(modId"=>105)
"MOD_THROW"=>0x6A,//ThrowSkill(modId"=>106)
"MOD_GUARD"=>0x6B,//GuardSkill(modId"=>107)
"MOD_EVASION"=>0x6C,//EvasionSkill(modId"=>108)
"MOD_SHIELD"=>0x6D,//ShieldSkill(modId"=>109)
"MOD_PARRY"=>0x6E,//ParrySkill(modId"=>110)
//MagicSkills
"MOD_DIVINE"=>0x6F,//DivineMagicSkill(modId"=>111)
"MOD_HEALING"=>0x70,//HealingMagicSkill(modId"=>112)
"MOD_ENHANCE"=>0x71,//EnhancingMagicSkill(modId"=>113)
"MOD_ENFEEBLE"=>0x72,//EnfeeblingMagicSkill(modId"=>114)
"MOD_ELEM"=>0x73,//ElementalMagicSkill(modId"=>115)
"MOD_DARK"=>0x74,//DarkMagicSkill(modId"=>116)
"MOD_SUMMONING"=>0x75,//SummoningMagicSkill(modId"=>117)
"MOD_NINJUTSU"=>0x76,//NinjutsuMagicSkill(modId"=>118)
"MOD_SINGING"=>0x77,//SingingMagicSkill(modId"=>119)
"MOD_STRING"=>0x78,//StringMagicSkill(modId"=>120)
"MOD_WIND"=>0x79,//WindMagicSkill(modId"=>121)
"MOD_BLUE"=>0x7A,//BlueMagicSkill(modId"=>122)
//SynthesisSkills
"MOD_FISH"=>0x7F,//FishingSkill(modId"=>127)
"MOD_WOOD"=>0x80,//WoodworkingSkill(modId"=>128)
"MOD_SMITH"=>0x81,//SmithingSkill(modId"=>129)
"MOD_GOLDSMITH"=>0x82,//GoldsmithingSkill(modId"=>130)
"MOD_CLOTH"=>0x83,//ClothcraftSkill(modId"=>131)
"MOD_LEATHER"=>0x84,//LeathercraftSkill(modId"=>132)
"MOD_BONE"=>0x85,//BonecraftSkill(modId"=>133)
"MOD_ALCHEMY"=>0x86,//AlchemySkill(modId"=>134)
"MOD_COOK"=>0x87,//CookingSkill(modId"=>135)
"MOD_SYNERGY"=>0x88,//SynergySkill(modId"=>136)
"MOD_RIDING"=>0x89,//RidingSkill(modId"=>137)
//Chanceyouwillnotmakeanhqsynth(ImpossibilityofHQsynth)
"MOD_ANTIHQ_WOOD"=>0x90,//WoodworkingSuccessRate%(modId"=>144)
"MOD_ANTIHQ_SMITH"=>0x91,//SmithingSuccessRate%(modId"=>145)
"MOD_ANTIHQ_GOLDSMITH"=>0x92,//GoldsmithingSuccessRate%(modId"=>146)
"MOD_ANTIHQ_CLOTH"=>0x93,//ClothcraftSuccessRate%(modId"=>147)
"MOD_ANTIHQ_LEATHER"=>0x94,//LeathercraftSuccessRate%(modId"=>148)
"MOD_ANTIHQ_BONE"=>0x95,//BonecraftSuccessRate%(modId"=>149)
"MOD_ANTIHQ_ALCHEMY"=>0x96,//AlchemySuccessRate%(modId"=>150)
"MOD_ANTIHQ_COOK"=>0x97,//CookingSuccessRate%(modId"=>151)
//Damage/CritDamage/Delay
"MOD_DMG"=>0xA0,//DamageTaken%(modId"=>160)
"MOD_DMGPHYS"=>0xA1,//PhysicalDamageTaken%(modId"=>161)
"MOD_DMGBREATH"=>0xA2,//BreathDamageTaken%(modId"=>162)
"MOD_DMGMAGIC"=>0xA3,//MagicDamageTaken%-256base!(valueof-24means-24/256magicdamagetaken)(modId"=>163)
"MOD_DMGRANGE"=>0xA4,//RangeDamageTaken%(modId"=>164)
"MOD_UDMGPHYS"=>0x183,//UncappedDamageMultipliers(modId"=>387)
"MOD_UDMGBREATH"=>0x184,//Usedinsentinal,invincible,physicalshieldetc(modId"=>388)
"MOD_UDMGMAGIC"=>0x185,//(modId"=>389)
"MOD_UDMGRANGE"=>0x186,//(modId"=>390)
"MOD_CRITHITRATE"=>0xA5,//Raiseschancetocrit(modId"=>165)
"MOD_CRIT_DMG_INCREASE"=>0x1A5,//Raisesthedamageofcritcalhitbypercent%(modId"=>421)
"MOD_ENEMYCRITRATE"=>0xA6,//Raiseschanceenemywillcrit(modId"=>166)
"MOD_HASTE_MAGIC"=>0xA7,//Haste(andSlow)frommagic-1024base!(448cap)(modId"=>167)
"MOD_HASTE_ABILITY"=>0x17F,//Haste(andSlow)fromabilities-1024base!(256cap?)(modId"=>383)
"MOD_HASTE_GEAR"=>0x180,//Haste(andSlow)fromequipment-1024base!(256cap)(modId"=>384)
"MOD_SPELLINTERRUPT"=>0xA8,//%SpellInterruptionRate(modId"=>168)
"MOD_MOVE"=>0xA9,//%MovementSpeed(modId"=>169)
"MOD_FASTCAST"=>0xAA,//IncreasesSpellCastTime(TRAIT)(modId"=>170)
"MOD_UFASTCAST"=>0x197,//uncappedfastcast(modId"=>407)
"MOD_DELAY"=>0xAB,//Increase/DecreaseDelay(modId"=>171)
"MOD_RANGED_DELAY"=>0xAC,//Increase/DecreaseRangedDelay(modId"=>172)
"MOD_MARTIAL_ARTS"=>0xAD,//TheintegeramountofdelaytoreducefromH2Hweapons'basedelay.(TRAIT)(modId"=>173)
"MOD_SKILLCHAINBONUS"=>0xAE,//Damagebonusappliedtoskillchaindamage.Modifierfromeffects/traits(modId"=>174)
"MOD_SKILLCHAINDMG"=>0xAF,//Damagebonusappliedtoskillchaindamage.Modifierfromgear(multiplicativeaftereffect/traits)(modId"=>175)
"MOD_MAGIC_DAMAGE"=>0x137,//Magicdamageaddeddirectlytothespell'sbasedamage(modId"=>311)
//FOOD!
"MOD_FOOD_HPP"=>0xB0,//(modId"=>176)
"MOD_FOOD_HP_CAP"=>0xB1,//(modId"=>177)
"MOD_FOOD_MPP"=>0xB2,//(modId"=>178)
"MOD_FOOD_MP_CAP"=>0xB3,//(modId"=>179)
"MOD_FOOD_ATTP"=>0xB4,//(modId"=>180)
"MOD_FOOD_ATT_CAP"=>0xB5,//(modId"=>181)
"MOD_FOOD_DEFP"=>0xB6,//(modId"=>182)
"MOD_FOOD_DEF_CAP"=>0xB7,//(modId"=>183)
"MOD_FOOD_ACCP"=>0xB8,//(modId"=>184)
"MOD_FOOD_ACC_CAP"=>0xB9,//(modId"=>185)
"MOD_FOOD_RATTP"=>0xBA,//(modId"=>186)
"MOD_FOOD_RATT_CAP"=>0xBB,//(modId"=>187)
"MOD_FOOD_RACCP"=>0xBC,//(modId"=>188)
"MOD_FOOD_RACC_CAP"=>0xBD,//(modId"=>190)
//Killer-Effects-(MostbyTraits/JobAbility)
"MOD_VERMIN_KILLER"=>0xE0,//Enhances"VerminKiller"effect(modId"=>224)
"MOD_BIRD_KILLER"=>0xE1,//Enhances"BirdKiller"effect(modId"=>225)
"MOD_AMORPH_KILLER"=>0xE2,//Enhances"AmorphKiller"effect(modId"=>226)
"MOD_LIZARD_KILLER"=>0xE3,//Enhances"LizardKiller"effect(modId"=>227)
"MOD_AQUAN_KILLER"=>0xE4,//Enhances"AquanKiller"effect(modId"=>228)
"MOD_PLANTOID_KILLER"=>0xE5,//Enhances"PlantiodKiller"effect(modId"=>229)
"MOD_BEAST_KILLER"=>0xE6,//Enhances"BeastKiller"effect(modId"=>230)
"MOD_UNDEAD_KILLER"=>0xE7,//Enhances"UndeadKiller"effect(modId"=>231)
"MOD_ARCANA_KILLER"=>0xE8,//Enhances"ArcanaKiller"effect(modId"=>232)
"MOD_DRAGON_KILLER"=>0xE9,//Enhances"DragonKiller"effect(modId"=>233)
"MOD_DEMON_KILLER"=>0xEA,//Enhances"DemonKiller"effect(modId"=>234)
"MOD_EMPTY_KILLER"=>0xEB,//Enhances"EmptyKiller"effect(modId"=>235)
"MOD_HUMANOID_KILLER"=>0xEC,//Enhances"HumanoidKiller"effect(modId"=>236)
"MOD_LUMORIAN_KILLER"=>0xED,//Enhances"LumorianKiller"effect(modId"=>237)
"MOD_LUMINION_KILLER"=>0xEE,//Enhances"LuminionKiller"effect(modId"=>238)
//Resistancestoenfeebles-Traits/JobAbility
"MOD_SLEEPRES"=>0xF0,//Enhances"ResistSleep"effect(modId"=>240)
"MOD_POISONRES"=>0xF1,//Enhances"ResistPoison"effect(modId"=>241)
"MOD_PARALYZERES"=>0xF2,//Enhances"ResistParalyze"effect(modId"=>242)
"MOD_BLINDRES"=>0xF3,//Enhances"ResistBlind"effect(modId"=>243)
"MOD_SILENCERES"=>0xF4,//Enhances"ResistSilence"effect(modId"=>244)
"MOD_VIRUSRES"=>0xF5,//Enhances"ResistVirus"effect(modId"=>245)
"MOD_PETRIFYRES"=>0xF6,//Enhances"ResistPetrify"effect(modId"=>246)
"MOD_BINDRES"=>0xF7,//Enhances"ResistBind"effect(modId"=>247)
"MOD_CURSERES"=>0xF8,//Enhances"ResistCurse"effect(modId"=>248)
"MOD_GRAVITYRES"=>0xF9,//Enhances"ResistGravity"effect(modId"=>249)
"MOD_SLOWRES"=>0xFA,//Enhances"ResistSlow"effect(modId"=>250)
"MOD_STUNRES"=>0xFB,//Enhances"ResistStun"effect(modId"=>251)
"MOD_CHARMRES"=>0xFC,//Enhances"ResistCharm"effect(modId"=>252)
"MOD_AMNESIARES"=>0xFD,//Enhances"ResistAmnesia"effect(modId"=>253)
//PLACEHOLDER"=>0xFE,//placeholderforfutureresisteffect(modId"=>254)
"MOD_DEATHRES"=>0xFF,//UsedbygearandATMAthatgiveresistancetoinstanceKO(modId"=>255)
"MOD_PARALYZE"=>0x101,//Paralyze--percentchancetoproc(modId"=>257)
"MOD_MIJIN_GAKURE"=>0x102,//Trackswhetherornotyouusedthisabilitytodie.(modId"=>258)
"MOD_DUAL_WIELD"=>0x103,//Percentreductionindualwielddelay.(modId"=>259)
//Warrior
"MOD_DOUBLE_ATTACK"=>0x120,//Percentchancetoproc(modId"=>288)
"MOD_WARCRY_DURATION"=>0x1E3,//Warcydurationbonusfromgear
//Monk
"MOD_SUBTLE_BLOW"=>0x121,//HowmuchTPtoreduce.(modId"=>289)
"MOD_COUNTER"=>0x123,//Percentchancetocounter(modId"=>291)
"MOD_KICK_ATTACK"=>0x124,//Percentchancetokick(modId"=>292)"MOD_PERFECT_COUNTER_ATT"=>0x1AC,//TODO:Raisesweapondamageby20whencounteringwhileunderthePerfectCountereffect.ThisalsoaffectsWeaponRank(thoughnotiffightingbarehanded).(modId"=>428)
"MOD_FOOTWORK_ATT_BONUS"=>0x1AD,//TODO:RaisestheattackbonusofFootwork.(TantraGaiters+2raise100/1024to152/1024)(modId"=>429)
//WhiteMage
"MOD_AFFLATUS_SOLACE"=>0x125,//PoolofHPaccumulatedduringAfflatusSolace(modId"=>293)
"MOD_AFFLATUS_MISERY"=>0x126,//PoolofHPaccumulatedduringAfflatusMisery(modId"=>294)
"MOD_AUSPICE_EFFECT"=>0x1E4,//BonustoAuspiceSubtleBlowEffect.
//BlackMage
"MOD_CLEAR_MIND"=>0x127,//UsedinconjunctionwithMOD_HEALMPtoincreaseamountbetweentics(modId"=>295)
"MOD_CONSERVE_MP"=>0x128,//Percentchance(modId"=>296)
//RedMage
"MOD_BLINK"=>0x12B,//Tracksblinkshadows(modId"=>299)
"MOD_STONESKIN"=>0x12C,//TracksstoneskinHPpool(modId"=>300)
"MOD_PHALANX"=>0x12D,//Tracksdirectdamagereduction(modId"=>301)
//Thief
"MOD_STEAL"=>0x12A,//Increase/DecreaseTHFStealchance(modId"=>298)
"MOD_TRIPLE_ATTACK"=>0x12E,//Percentchance(modId"=>302)
"MOD_TREASURE_HUNTER"=>0x12F,//Percentchance(modId"=>303)
//Paladin
"MOD_ABSORB_PHYSDMG_TO_MP"=>0x1AA,//AbsorbsapercentageofphysicaldamagetakentoMP.(modId"=>426)
"MOD_ENMITY_REDUCTION_PHYSICAL"=>0x1AB,//TODO:ReducesEnmitydecreasewhentakingphysicaldamage(modId"=>427)
"MOD_SHIELD_MASTERY_TP"=>0x1E5,//ShieldmasteryTPbonuswhenblockingwithashield(modId"=>485)
//DarkKnight
//Nothinghereyet..
//Beastmaster
"MOD_TAME"=>0x130,//Additionalpercentchancetocharm(modId"=>304)
"MOD_CHARM_TIME"=>0x168,//extendsthecharmtimeonly,noeffectofcharmchance(modId"=>360)
"MOD_REWARD_HP_BONUS"=>0x16C,//PercenttoaddtorewardHPhealed.(364)(modId"=>364)
"MOD_CHARM_CHANCE"=>0x187,//extrachancetocharm(light+apollostaffect)(modId"=>391)
"MOD_FERAL_HOWL_DURATION"=>0x1F7,//+20%durationpermeritwhenwearingaugmentedMonsterJackcoat+2(modId"=>503)
//Bard
"MOD_MINNE_EFFECT"=>0x1B1,//(modId"=>433)
"MOD_MINUET_EFFECT"=>0x1B2,//(modId"=>434)
"MOD_PAEON_EFFECT"=>0x1B3,//(modId"=>435)
"MOD_REQUIEM_EFFECT"=>0x1B4,//(modId"=>436)
"MOD_THRENODY_EFFECT"=>0x1B5,//(modId"=>437)
"MOD_MADRIGAL_EFFECT"=>0x1B6,//(modId"=>438)
"MOD_MAMBO_EFFECT"=>0x1B7,//(modId"=>439)
"MOD_LULLABY_EFFECT"=>0x1B8,//(modId"=>440)
"MOD_ETUDE_EFFECT"=>0x1B9,//(modId"=>441)
"MOD_BALLAD_EFFECT"=>0x1BA,//(modId"=>442)
"MOD_MARCH_EFFECT"=>0x1BB,//(modId"=>443)
"MOD_FINALE_EFFECT"=>0x1BC,//(modId"=>444)
"MOD_CAROL_EFFECT"=>0x1BD,//(modId"=>445)
"MOD_MAZURKA_EFFECT"=>0x1BE,//(modId"=>446)
"MOD_ELEGY_EFFECT"=>0x1BF,//(modId"=>447)
"MOD_PRELUDE_EFFECT"=>0x1C0,//(modId"=>448)
"MOD_HYMNUS_EFFECT"=>0x1C1,//(modId"=>449)
"MOD_VIRELAI_EFFECT"=>0x1C2,//(modId"=>450)
"MOD_SCHERZO_EFFECT"=>0x1C3,//(modId"=>451)
"MOD_ALL_SONGS_EFFECT"=>0x1C4,//(modId"=>452)
"MOD_MAXIMUM_SONGS_BONUS"=>0x1C5,//(modId"=>453)
"MOD_SONG_DURATION_BONUS"=>0x1C6,//(modId"=>454)
"MOD_SONG_SPELLCASTING_TIME"=>0x1C7,//(modId"=>455)
//Ranger
"MOD_RECYCLE"=>0x131,//Percentchancetorecycle(modId"=>305)
"MOD_SNAP_SHOT"=>0x16D,//Percentreductiontorangeattackdelay(modId"=>365)
"MOD_RAPID_SHOT"=>0x167,//Percentchancetoprocrapidshot(modId"=>359)
"MOD_WIDESCAN"=>0x154,//(modId"=>340)
"MOD_BARRAGE_ACC"=>0x1A4,//Barrageaccuracy(modId"=>420)
"MOD_DOUBLE_SHOT_RATE"=>0x1A6,//Theratethatdoubleshotcanproc.Withoutthis,thedefaultis40%.(modId"=>422)
"MOD_VELOCITY_SNAPSHOT_BONUS"=>0x1A7,//IncreasesSnapshotwhilstVelocityShotisup.(modId"=>423)
"MOD_VELOCITY_RATT_BONUS"=>0x1A8,//IncreasesRangedAttackwhilstVelocityShotisup.(modId"=>424)
"MOD_SHADOW_BIND_EXT"=>0x1A9,//Extendsthetimeofshadowbind(modId"=>425)
"MOD_SCAVENGE_EFFECT"=>0x138,//(modId"=>312)
//Samurai
"MOD_ZANSHIN"=>0x132,//Zanshinpercentchance(modId"=>306)
//Ninja
"MOD_UTSUSEMI"=>0x133,//Everyone'sfavorite--tracksshadows.(modId"=>307)
"MOD_NINJA_TOOL"=>0x134,//Percentchancetonotuseatool.(modId"=>308)
//Dragoon
"MOD_JUMP_TP_BONUS"=>0x169,//bonustpplayerreceiveswhenusingjump(mustbedividedby10)(modId"=>361)
"MOD_JUMP_ATT_BONUS"=>0x16A,//ATT%bonusforjump+highjump(modId"=>362)
"MOD_HIGH_JUMP_ENMITY_REDUCTION"=>0x16B,//forgearthatreducesmoreenmityfromhighjump(modId"=>363)
//Summoner
"MOD_AVATAR_PERPETUATION"=>0x173,//storesbasecostofcurrentavatar(modId"=>371)
"MOD_WEATHER_REDUCTION"=>0x174,//storesperpetuationreductiondependingonweather(modId"=>372)
"MOD_DAY_REDUCTION"=>0x175,//storesperpetuationreductiondependingonday(modId"=>373)
"MOD_PERPETUATION_REDUCTION"=>0x15A,//storestheMP/tickreductionfromgear(modId"=>346)
"MOD_BP_DELAY"=>0x165,//storesbloodpactdelayreduction(modId"=>357)
//BlueMage
"MOD_BLUE_POINTS"=>0x135,//Tracksextrabluepoints(modId"=>309)
//Corsair
"MOD_EXP_BONUS"=>0x17E,//(modId"=>382)
"MOD_DMG_REFLECT"=>0x13C,//Trackstotals(modId"=>316)
"MOD_ROLL_ROGUES"=>0x13D,//Trackstotals(modId"=>317)
"MOD_ROLL_GALLANTS"=>0x13E,//Trackstotals(modId"=>318)
"MOD_ROLL_CHAOS"=>0x13F,//Trackstotals(modId"=>319)
"MOD_ROLL_BEAST"=>0x140,//Trackstotals(modId"=>320)
"MOD_ROLL_CHORAL"=>0x141,//Trackstotals(modId"=>321)
"MOD_ROLL_HUNTERS"=>0x142,//Trackstotals(modId"=>322)
"MOD_ROLL_SAMURAI"=>0x143,//Trackstotals(modId"=>323)
"MOD_ROLL_NINJA"=>0x144,//Trackstotals(modId"=>324)
"MOD_ROLL_DRACHEN"=>0x145,//Trackstotals(modId"=>325)
"MOD_ROLL_EVOKERS"=>0x146,//Trackstotals(modId"=>326)
"MOD_ROLL_MAGUS"=>0x147,//Trackstotals(modId"=>327)
"MOD_ROLL_CORSAIRS"=>0x148,//Trackstotals(modId"=>328)
"MOD_ROLL_PUPPET"=>0x149,//Trackstotals(modId"=>329)
"MOD_ROLL_DANCERS"=>0x14A,//Trackstotals(modId"=>330)
"MOD_ROLL_SCHOLARS"=>0x14B,//Trackstotals(modId"=>331)
"MOD_BUST"=>0x14C,//#ofbusts(modId"=>332)
"MOD_QUICK_DRAW_DMG"=>0x19B,//(modId"=>411)
//Puppetmaster
"MOD_MANEUVER_BONUS"=>0x1F8,//(modId"=>504)ManeuverStatBonus
"MOD_OVERLOAD_THRESH"=>0x1F9,//(modId"=>505)OverloadThresholdBonus
//Dancer
"MOD_FINISHING_MOVES"=>0x14D,//Tracks#offinishingmoves(modId"=>333)
"MOD_SAMBA_DURATION"=>0x1EA,//Sambadurationbonus(modId"=>490)
"MOD_WALTZ_POTENTCY"=>0x1EB,//WaltzPotentcyBonus(modId"=>491)
"MOD_CHOCO_JIG_DURATION"=>0x1EC,//Jigdurationbonus(modId"=>492)
"MOD_VFLOURISH_MACC"=>0x1ED,//ViolentFlourishaccuracybonus(modId"=>493)
"MOD_STEP_FINISH"=>0x1EE,//Bonusfinishingmovesfromsteps(modId"=>494)
"MOD_STEP_ACCURACY"=>0x193,//BonusaccuracyforDancer'ssteps(modId"=>403)
"MOD_SPECTRAL_JIG"=>0x1EF,//SpectralJigdurationmodifier(percentincrease)(modId"=>495)
"MOD_WALTZ_RECAST"=>0x1F1,//(modID"=>497)Waltzrecastmodifier(percent)
"MOD_SAMBA_PDURATION"=>0x1F2,//(modID"=>498)Sambapercentdurationbonus
//Scholar
"MOD_BLACK_MAGIC_COST"=>0x189,//MPcostforblackmagic(light/darkarts)(modId"=>393)
"MOD_WHITE_MAGIC_COST"=>0x18A,//MPcostforwhitemagic(light/darkarts)(modId"=>394)
"MOD_BLACK_MAGIC_CAST"=>0x18B,//Casttimeforblackmagic(light/darkarts)(modId"=>395)
"MOD_WHITE_MAGIC_CAST"=>0x18C,//Casttimeforblackmagic(light/darkarts)(modId"=>396)
"MOD_BLACK_MAGIC_RECAST"=>0x18D,//Recasttimeforblackmagic(light/darkarts)(modId"=>397)
"MOD_WHITE_MAGIC_RECAST"=>0x18E,//Recasttimeforwhitemagic(light/darkarts)(modId"=>398)
"MOD_ALACRITY_CELERITY_EFFECT"=>0x18F,//Bonusforcelerity/alacrityeffect(modId"=>399)
"MOD_LIGHT_ARTS_EFFECT"=>0x14E,//(modId"=>334)
"MOD_DARK_ARTS_EFFECT"=>0x14F,//(modId"=>335)
"MOD_LIGHT_ARTS_SKILL"=>0x150,//(modId"=>336)
"MOD_DARK_ARTS_SKILL"=>0x151,//(modId"=>337)
"MOD_REGEN_EFFECT"=>0x152,//(modId"=>338)
"MOD_REGEN_DURATION"=>0x153,//(modId"=>339)
"MOD_HELIX_EFFECT"=>0x1DE,//(modId"=>478)
"MOD_HELIX_DURATION"=>0x1DD,//(modId"=>477)
"MOD_STORMSURGE_EFFECT"=>0x190,//(modId"=>400)
"MOD_SUBLIMATION_BONUS"=>0x191,//(modId"=>401)
"MOD_GRIMOIRE_SPELLCASTING"=>0x1E9,//(modID"=>489)"Grimoire:Reducesspellcastingtime"bonus
"MOD_ENSPELL"=>0x155,//storesthetypeofenspellactive(0ifnothing)(modId"=>341)
"MOD_ENSPELL_DMG"=>0x157,//storesthebasedamageoftheenspellbeforereductions(modId"=>343)
"MOD_ENSPELL_DMG_BONUS"=>0x1B0,//(modId"=>432)
"MOD_SPIKES"=>0x156,//storethetypeofspikespellactive(0ifnothing)(modId"=>342)
"MOD_SPIKES_DMG"=>0x158,//storesthebasedamageofthespikesbeforereductions(modId"=>344)
"MOD_TP_BONUS"=>0x159,//(modId"=>345)
//storestheamountofelementalaffinity(elementalstavesmostly)
"MOD_FIRE_AFFINITY"=>0x15B,//FireAffinity(modId"=>347)
"MOD_EARTH_AFFINITY"=>0x15C,//EarthAffinity(modId"=>348)
"MOD_WATER_AFFINITY"=>0x15D,//WaterAffinity(modId"=>349)
"MOD_ICE_AFFINITY"=>0x15E,//IceAffinity(modId"=>350)
"MOD_THUNDER_AFFINITY"=>0x15F,//LightningAffinity(modId"=>351)
"MOD_WIND_AFFINITY"=>0x160,//WindAffinity(modId"=>352)
"MOD_LIGHT_AFFINITY"=>0x161,//LightAffinity(modId"=>353)
"MOD_DARK_AFFINITY"=>0x162,//DarkAffinity(modId"=>354)
//SpecialModifier+
"MOD_ADDS_WEAPONSKILL"=>0x163,//(modId"=>355)
"MOD_ADDS_WEAPONSKILL_DYN"=>0x164,//InDynamis(modId"=>356)
"MOD_STEALTH"=>0x166,//(modId"=>358)
"MOD_MAIN_DMG_RATING"=>0x16E,//addsdamageratingtomainhandweapon(maneater/blaudolchetchiddeneffects)(modId"=>366)
"MOD_SUB_DMG_RATING"=>0x16F,//addsdamageratingtooffhandweapon(modId"=>367)
"MOD_REGAIN"=>0x170,//autoregainTP(fromitems)|thisismultipliedby10e.g.20is2%TP(modId"=>368)
"MOD_REGAIN_DOWN"=>0x196,//plague,reducetp(modId"=>406)
"MOD_REFRESH"=>0x171,//autorefreshfromequipment(modId"=>369)
"MOD_REFRESH_DOWN"=>0x195,//plague,reducemp(modId"=>405)
"MOD_REGEN"=>0x172,//autoregenfromequipment(modId"=>370)
"MOD_REGEN_DOWN"=>0x194,//poison(modId"=>404)
"MOD_CURE_POTENCY"=>0x176,//%curepotency|bonusfromgeariscappedat50(modId"=>374)
"MOD_CURE_POTENCY_RCVD"=>0x177,//%potencyofreceivedcure|healer'sroll,someitemshavethis(modId"=>375)
"MOD_RANGED_DMG_RATING"=>0x178,//addsdamageratingtorangedweapon(modId"=>376)
"MOD_MAIN_DMG_RANK"=>0x179,//addsweaponranktomainweapon(modId"=>377)(http://wiki.bluegartr.com/bg/Weapon_Rank)
"MOD_SUB_DMG_RANK"=>0x17A,//addsweaponranktosubweapon(modId"=>378)
"MOD_RANGED_DMG_RANK"=>0x17B,//addsweaponranktorangedweapon(modId"=>379)
"MOD_DELAYP"=>0x17C,//delayadditionpercent(doesnotaffecttpgain)(modId"=>380)
"MOD_RANGED_DELAYP"=>0x17D,//rangeddelayadditionpercent(doesnotaffecttpgain)(modId"=>381)
"MOD_SHIELD_BASH"=>0x181,//(modId"=>385)
"MOD_KICK_DMG"=>0x182,//increaseskickattackdamage(modId"=>386)
"MOD_WEAPON_BASH"=>0x188,//(modId"=>392)
"MOD_WYVERN_BREATH"=>0x192,//(modId"=>402)
///Gearsetmodifiers
"MOD_DA_DOUBLE_DAMAGE"=>0x198,//Doubleattack'sdoubledamagechance%.(modId"=>408)
"MOD_TA_TRIPLE_DAMAGE"=>0x199,//Tripleattack'stripledamagechance%.(modId"=>409)
"MOD_ZANSHIN_DOUBLE_DAMAGE"=>0x19A,//Zanshin'sdoubledamagechance%.(modId"=>410)
"MOD_RAPID_SHOT_DOUBLE_DAMAGE"=>0x1DF,//Rapidshot'sdoubledamagechance%.(modId"=>479)
"MOD_ABSORB_DMG_CHANCE"=>0x1E0,//Chancetoabsorbdamage%(modId"=>480)
"MOD_EXTRA_DUAL_WIELD_ATTACK"=>0x1E1,//Chancetolandanextraattackwhendualwielding(modId"=>481)
"MOD_EXTRA_KICK_ATTACK"=>0x1E2,//OccasionallyallowsasecondKickAttackduringanattackroundwithouttheuseofFootwork.(modId"=>482)
"MOD_SAMBA_DOUBLE_DAMAGE"=>0x19F,//Doubledamagechancewhensambaisup.(modId"=>415)
"MOD_NULL_PHYSICAL_DAMAGE"=>0x1A0,//ChancetoNULLphysicaldamage.(modId"=>416)
"MOD_QUICK_DRAW_TRIPLE_DAMAGE"=>0x1A1,//Chancetodotripledamagewithquickdraw.(modId"=>417)
"MOD_BAR_ELEMENT_NULL_CHANCE"=>0x1A2,//BarElementalspellswilloccasionallyNULLifydamageofthesameelement.(modId"=>418)
"MOD_GRIMOIRE_INSTANT_CAST"=>0x1A3,//SpellsthatmatchyourcurrentArtswilloccasionallycastinstantly,withoutrecast.(modId"=>419)
"MOD_QUAD_ATTACK"=>0x1AE,//Quadrupleattackchance.(modId"=>430)
//Reraise(AutoReraise,usedbygear)
"MOD_RERAISE_I"=>0x1C8,//Reraise.(modId"=>456)
"MOD_RERAISE_II"=>0x1C9,//ReraiseII.(modId"=>457)
"MOD_RERAISE_III"=>0x1CA,//ReraiseIII.(modId"=>458)
//ElementalAbsorbChance
"MOD_FIRE_ABSORB"=>0x1CB,//(modId"=>459)
"MOD_EARTH_ABSORB"=>0x1CC,//(modId"=>460)
"MOD_WATER_ABSORB"=>0x1CD,//(modId"=>461)
"MOD_WIND_ABSORB"=>0x1CE,//(modId"=>462)
"MOD_ICE_ABSORB"=>0x1CF,//(modId"=>463)
"MOD_LTNG_ABSORB"=>0x1D0,//(modId"=>464)
"MOD_LIGHT_ABSORB"=>0x1D1,//(modId"=>465)
"MOD_DARK_ABSORB"=>0x1D2,//(modId"=>466)
//ElementalNullChance
"MOD_FIRE_NULL"=>0x1D3,//(modId"=>467)
"MOD_EARTH_NULL"=>0x1D4,//(modId"=>468)
"MOD_WATER_NULL"=>0x1D5,//(modId"=>469)
"MOD_WIND_NULL"=>0x1D6,//(modId"=>470)
"MOD_ICE_NULL"=>0x1D7,//(modId"=>471)
"MOD_LTNG_NULL"=>0x1D8,//(modId"=>472)
"MOD_LIGHT_NULL"=>0x1D9,//(modId"=>473)
"MOD_DARK_NULL"=>0x1DA,//(modId"=>474)
"MOD_MAGIC_ABSORB"=>0x1DB,//(modId"=>475)
"MOD_MAGIC_NULL"=>0x1DC,//(modId"=>476)
"MOD_PHYS_ABSORB"=>0x200,//(modId"=>512)
"MOD_ABSORB_DMG_TO_MP"=>0x204,//(modId"=>516)UnlikePLDgearmod,worksonalldamagetypes(EtherealEarring)
"MOD_ADDITIONAL_EFFECT"=>0x1AF,//(modId"=>431)
"MOD_ITEM_SPIKES_TYPE"=>0x1F3,//Typespikesanitemhas(modId"=>499)
"MOD_ITEM_SPIKES_DMG"=>0x1F4,//Damageofanitemsspikes(modId"=>500)
"MOD_ITEM_SPIKES_CHANCE"=>0x1F5,//Chanceofanitemsspikeproc(modId"=>501)
"MOD_GOV_CLEARS"=>0x1F0,//4%bonusperGroundsofValorPageclear(modId"=>496)
"MOD_EXTRA_DMG_CHANCE"=>0x1FA,//ProcrateofMOD_OCC_DO_EXTRA_DMG.111wouldbe11.1%(modId"=>506)
"MOD_OCC_DO_EXTRA_DMG"=>0x1FB,//Multiplierfor"Occasionallydoxtimesnormaldamage".250wouldbe2.5timesdamage.(modId"=>507)
"MOD_EAT_RAW_FISH"=>0x19C,//(modId"=>412)
"MOD_EAT_RAW_MEAT"=>0x19D,//(modId"=>413)
"MOD_ENHANCES_CURSNA"=>0x136,//Usedbygearwiththe"EnhancesCursna"attribute(modId"=>310)
"MOD_RETALIATION"=>0x19E,//IncreasesdamageofRetaliationhits(modId"=>414)
"MOD_AUGMENTS_THIRD_EYE"=>0x1FC,//Addscounterto3rdeyeanticipates&ifusingSeigancounterrateisincreasedby15%(modId"=>508)
"MOD_CLAMMING_IMPROVED_RESULTS"=>0x1FD,//(modId"=>509)
"MOD_CLAMMING_REDUCED_INCIDENTS"=>0x1FE,//(modId"=>510)
"MOD_CHOCOBO_RIDING_TIME"=>0x1FF,//Increaseschocoboridingtime(modId"=>511)
"MOD_HARVESTING_RESULT"=>0x201,//Improvesharvestingresults(modId"=>513)
"MOD_LOGGING_RESULT"=>0x202,//Improvesloggingresults(modId"=>514)
"MOD_MINNING_RESULT"=>0x203,//Improvesminingresults(modId"=>515)
"MOD_EGGHELM"=>0x205,
"MOD_SHIELDBLOCKRATE"=>0x206,//Affectsshieldblockrate,percentbased(modID"=>518)
"MOD_DIA_DOT"=>0x139,//IncreasestheDoTdamageofDia(modId"=>313)
//MOD_SPARE"=>0x13A,//(modId"=>314)
//MOD_SPARE"=>0x13B,//(modId"=>315)
//MOD_SPARE"=>0x207,//(modId"=>519)
);
$mod_name=array_flip($mods);

 $mission_array = array(
1 => "Current Sandy Mission",
3 => "SMASH THE ORCISH SCOUTS",
4 => "BAT HUNT",
5 => "SAVE THE CHILDREN",
6 => "THE RESCUE DRILL",
7 => "THE DAVOI REPORT",
8 => "JOURNEY ABROAD",
9 => "JOURNEY TO BASTOK",
10 => "JOURNEY TO WINDURST",
11 => "JOURNEY TO BASTOK2",
12 => "JOURNEY TO WINDURST2",
13 => "INFILTRATE DAVOI",
14 => "THE CRYSTAL SPRING",
15 => "APPOINTMENT TO JEUNO",
16 => "MAGICITE SAN D ORIA",
17 => "THE RUINS OF FEI YIN",
18 => "THE SHADOW LORD",
19 => "LEAUTE S LAST WISHES",
20 => "RANPERRE S FINAL REST",
21 => "PRESTIGE OF THE PAPSQUE",
22 => "THE SECRET WEAPON",
23 => "COMING OF AGE",
24 => "LIGHTBRINGER",
25 => "BREAKING BARRIERS",
26 => "THE HEIR TO THE LIGHT",
67 => "Current Bastok Mission",
69 => "THE ZERUHN REPORT",
70 => "GEOLOGICAL SURVEY",
71 => "FETICHISM",
72 => "THE CRYSTAL LINE",
73 => "WADING BEASTS",
74 => "THE EMISSARY",
75 => "THE EMISSARY SANDORIA",
76 => "THE EMISSARY WINDURST",
77 => "THE EMISSARY SANDORIA2",
78 => "THE EMISSARY WINDURST2",
79 => "THE FOUR MUSKETEERS",
80 => "TO THE FORSAKEN MINES",
81 => "JEUNO MISSION",
82 => "MAGICITE BASTOK",
83 => "DARKNESS RISING",
84 => "XARCABARD LAND OF TRUTHS",
85 => "RETURN OF THE TALEKEEPER",
86 => "THE PIRATE S COVE",
87 => "THE FINAL IMAGE",
88 => "ON MY WAY",
89 => "THE CHAINS THAT BIND US",
90 => "ENTER THE TALEKEEPER",
91 => "THE SALT OF THE EARTH",
92 => "WHERE TWO PATHS CONVERGE",
133 => "Current Windy Mission",
135 => "THE HORUTOTO RUINS EXPERIMENT",
136 => "THE HEART OF THE MATTER",
137 => "THE PRICE OF PEACE",
138 => "LOST FOR WORDS",
139 => "A TESTING TIME",
140 => "THE THREE KINGDOMS",
141 => "THE THREE KINGDOMS SANDORIA",
142 => "THE THREE KINGDOMS BASTOK",
143 => "THE THREE KINGDOMS SANDORIA2",
144 => "THE THREE KINGDOMS BASTOK2",
145 => "TO EACH HIS OWN RIGHT",
146 => "WRITTEN IN THE STARS",
147 => "A NEW JOURNEY",
148 => "MAGICITE",
149 => "THE FINAL SEAL",
150 => "THE SHADOW AWAITS",
151 => "FULL MOON FOUNTAIN",
152 => "SAINTLY INVITATION",
153 => "THE SIXTH MINISTRY",
154 => "AWAKENING OF THE GODS",
155 => "VAIN",
156 => "THE JESTER WHO D BE KING",
157 => "DOLL OF THE DEAD",
158 => "MOON READING",
199 => "Current Zilart Mission",
201 => "THE NEW FRONTIER",
205 => "WELCOME TNORG",
207 => "KAZAMS CHIEFTAINESS",
209 => "THE TEMPLE OF UGGALEPIH",
211 => "HEADSTONE PILGRIMAGE",
213 => "THROUGH THE QUICKSAND CAVES",
215 => "THE CHAMBER OF ORACLES",
217 => "RETURN TO DELKFUTTS TOWER",
219 => "ROMAEVE",
221 => "THE TEMPLE OF DESOLATION",
223 => "THE HALL OF THE GODS",
224 => "THE MITHRA AND THE CRYSTAL",
225 => "THE GATE OF THE GODS",
227 => "ARK ANGELS",
228 => "THE SEALED SHRINE",
229 => "THE CELESTIAL NEXUS",
231 => "AWAKENING",
232 => "THE LAST VERSE",
265 => "Current TOAU Mission",
267 => "LAND OF SACRED SERPENTS",
268 => "IMMORTAL SENTRIES",
269 => "PRESIDENT SALAHEEM",
270 => "KNIGHT OF GOLD",
271 => "CONFESSIONS OF ROYALTY",
272 => "EASTERLY WINDS",
273 => "WESTERLY WINDS",
274 => "A MERCENARY LIFE",
275 => "UNDERSEA SCOUTING",
276 => "ASTRAL WAVES",
277 => "IMPERIAL SCHEMES",
278 => "ROYAL PUPPETEER",
279 => "LOST KINGDOM",
280 => "THE DOLPHIN CREST",
281 => "THE BLACK COFFIN",
282 => "GHOSTS OF THE PAST",
283 => "GUESTS OF THE EMPIRE",
284 => "PASSING GLORY",
285 => "SWEETS FOR THE SOUL",
286 => "TEAHOUSE TUMULT",
287 => "FINDERS KEEPERS",
288 => "SHIELD OF DIPLOMACY",
289 => "SOCIAL GRACES",
290 => "FOILED AMBITION",
291 => "PLAYING THE PART",
292 => "SEAL OF THE SERPENT",
293 => "MISPLACED NOBILITY",
294 => "BASTION OF KNOWLEDGE",
295 => "PUPPET IN PERIL",
296 => "PREVALENCE OF PIRATES",
297 => "SHADES OF VENGEANCE",
298 => "IN THE BLOOD",
299 => "SENTINELS HONOR",
300 => "TESTING THE WATERS",
301 => "LEGACY OF THE LOST",
302 => "GAZE OF THE SABOTEUR",
303 => "PATH OF BLOOD",
304 => "STIRRINGS OF WAR",
305 => "ALLIED RUMBLINGS",
306 => "UNRAVELING REASON",
307 => "LIGHT OF JUDGMENT",
308 => "PATH OF DARKNESS",
309 => "FANGS OF THE LION",
310 => "NASHMEIRAS PLEA",
311 => "URHGAN MISSION 44",
312 => "IMPERIAL CORONATION",
313 => "THE EMPRESS CROWNED",
314 => "ETERNAL MERCENARY",
331 => "Current WoTG Mission",
333 => "CAVERNOUS MAWS",
334 => "BACK TO THE BEGINNING",
335 => "CAIT SITH",
336 => "THE QUEEN OF THE DANCE",
337 => "WHILE THE CAT IS AWAY",
338 => "A TIMESWEPT BUTTERFLY",
339 => "PURPLE THE NEW BLACK",
340 => "IN THE NAME OF THE FATHER",
341 => "DANCERS IN DISTRESS",
342 => "DAUGHTER OF A KNIGHT",
343 => "A SPOONFUL OF SUGAR",
344 => "AFFAIRS OF STATE",
345 => "BORNE BY THE WIND",
346 => "A NATION ON THE BRINK",
347 => "CROSSROADS OF TIME",
348 => "SANDSWEPT MEMORIES",
349 => "NORTHLAND EXPOSURE",
350 => "TRAITOR IN THE MIDST",
351 => "BETRAYAL AT BEAUCEDINE",
352 => "ON THIN ICE",
353 => "PROOF OF VALOR",
354 => "A SANGUINARY PRELUDE",
355 => "DUNGEONS AND DANCERS",
356 => "DISTORTER OF TIME",
357 => "THE WILL OF THE WORLD",
358 => "FATE IN HAZE",
359 => "THE SCENT OF BATTLE",
360 => "ANOTHER WORLD",
361 => "A HAWK IN REPOSE",
362 => "THE BATTLE OF XARCABARD",
363 => "PRELUDE TO A STORM",
364 => "STORM S CRESCENDO",
365 => "INTO THE BEAST S MAW",
366 => "THE HUNTER ENSNARED",
367 => "FALL OF THE HAWK",
368 => "DARKNESS DESCENDS",
369 => "ADIEU LILISETTE",
370 => "BY THE FADING LIGHT",
371 => "EDGE OF EXISTENCE",
372 => "HER MEMORIES",
373 => "FORGET ME NOT",
374 => "PILLAR OF HOPE",
375 => "GLIMMER OF LIFE",
376 => "TIME SLIPS AWAY",
377 => "WHEN WILLS COLLIDE",
378 => "WHISPERS OF DAWN",
379 => "A DREAMY INTERLUDE",
380 => "CAIT IN THE WOODS",
381 => "FORK IN THE ROAD",
382 => "MAIDEN OF THE DUSK",
383 => "WHERE IT ALL BEGAN",
384 => "A TOKEN OF TROTH",
385 => "LEST WE FORGET",
397 => "Current COP Mission",
399 => "ANCIENT FLAMES BECKON",
400 => "THE RITES OF LIFE",
401 => "BELOW THE ARKS",
402 => "THE MOTHERCRYSTALS",
404 => "AN INVITATION WEST",
414 => "THE LOST CITY",
415 => "DISTANT BELIEFS",
416 => "AN ETERNAL MELODY",
417 => "ANCIENT VOWS",
419 => "THE CALL OF THE WYRMKING",
426 => "A VESSEL WITHOUT A CAPTAIN",
427 => "THE ROAD FORKS",
428 => "DESCENDANTS OF A LINE LOST",
429 => "COMEDY OF ERRORS ACT I",
430 => "TENDING AGED WOUNDS",
431 => "DARKNESS NAMED",
432 => "SHELTERING DOUBT",
439 => "THE SAVAGE",
440 => "THE SECRETS OF WORSHIP",
441 => "SLANDEROUS UTTERINGS",
442 => "THE ENDURING TUMULT OF WAR",
451 => "DESIRES OF EMPTINESS",
453 => "THREE PATHS",
459 => "FOR WHOM THE VERSE IS SUNG",
464 => "A PLACE TO RETURN",
465 => "MORE QUESTIONS THAN ANSWERS",
466 => "ONE TO BE FEARED",
467 => "CHAINS AND BONDS",
476 => "FLAMES IN THE DARKNESS",
477 => "FIRE IN THE EYES OF MEN",
479 => "CALM BEFORE THE STORM",
480 => "THE WARRIOR S PATH",
486 => "GARDEN OF ANTIQUITY",
489 => "A FATE DECIDED",
490 => "WHEN ANGELS FALL",
491 => "DAWN",
493 => "THE LAST VERSE",
529 => "Current Campaign Mission",
595 => "Current ACP Mission",
597 => "A CRYSTALLINE PROPHECY",
598 => "THE ECHO AWAKENS",
599 => "GATHERER OF LIGHT I",
600 => "GATHERER OF LIGHT II",
601 => "THOSE WHO LURK IN SHADOWS I",
602 => "THOSE WHO LURK IN SHADOWS II",
603 => "THOSE WHO LURK IN SHADOWS III",
604 => "REMEMBER ME IN YOUR DREAMS",
605 => "BORN OF HER NIGHTMARES",
606 => "BANISHING THE ECHO",
607 => "ODE OF LIFE BESTOWING",
608 => "A CRYSTALLINE PROPHECY FIN",
661 => "Current MKD Mission",
663 => "A MOOGLE KUPO DETAT",
664 => "DRENCHED IT BEGAN WITH A RAINDROP",
665 => "HASTEN IN A JAM IN JEUNO",
666 => "WELCOME TO MY DECREPIT DOMICILE",
667 => "CURSES A HORRIFICALLY HARROWING HEX",
668 => "AN ERRAND THE PROFESSORS PRICE",
669 => "SHOCK ARRANT ABUSE OF AUTHORITY",
670 => "LENDER BEWARE READ THE FINE PRINT",
671 => "RESCUE A MOOGLES LABOR OF LOVE",
672 => "ROAR A CAT BURGLAR BARES HER FANGS",
673 => "RELIEF A TRIUMPHANT RETURN",
674 => "JOY SUMMONED TO A FABULOUS FETE",
675 => "A CHALLENGE YOU COULD BE A WINNER",
676 => "SMASH A MALEVOLENT MENACE",
677 => "A MOOGLE KUPO DETAT FIN",
727 => "Current ASA Mission",
729 => "A SHANTOTTO ASCENSION",
730 => "BURGEONING DREAD",
731 => "THAT WHICH CURDLES BLOOD",
732 => "SUGAR COATED DIRECTIVE",
733 => "ENEMY OF THE EMPIRE I",
734 => "ENEMY OF THE EMPIRE II",
735 => "SUGAR COATED SUBTERFUGE",
736 => "SHANTOTTO IN CHAINS",
737 => "FOUNTAIN OF TROUBLE",
738 => "BATTARU ROYALE",
739 => "ROMANCING THE CLONE",
740 => "SISTERS IN ARMS",
741 => "PROJECT SHANTOTTOFICATION",
742 => "AN UNEASY PEACE",
743 => "A SHANTOTTO ASCENSION FIN",
793 => "Current SOA Mission",
795 => "RUMORS FROM THE WEST",
796 => "THE GEOMAGNETRON",
797 => "ONWARD TO ADOULIN",
798 => "HEARTWIGNS AND THE KINDHEARTED",
799 => "PIONEER REGISTRATION",
800 => "LIFE ON THE FRONTIER",
801 => "MEETING OF THE MINDS",
802 => "ARCIELA APPEARS AGAIN",
803 => "BUILDING PROSPECTS",
804 => "THE LIGHT SHINING IN YOUR EYES",
805 => "THE HEIRLOOM",
806 => "AN AIMLESS JOURNEY",
807 => "ORTHARSYNE",
808 => "IN THE PRESENCE OF ROYALTY",
809 => "THE TWIN WORLD TREES",
810 => "HONOR AND AUDACITY",
811 => "THE WATERGARDEN COLISEUM",
812 => "FRICTION AND FISSURES",
813 => "THE CELENNIA MEMORIAL LIBRARY",
814 => "FOR WHOM DO WE TOIL",
815 => "AIMING FOR YGNAS",
816 => "CALAMITY IN THE KITCHEN",
817 => "ARCIELA S PROMISE",
818 => "PREDATOR AND PREY",
819 => "BEHIND THE SLUICES",
820 => "THE LEAFKIN MONARCH",
821 => "YGGDRASIL",
822 => "RETURN OF THE EXORCIST",
823 => "THE MERCILESS ONE",
824 => "A CURSE FROM THE PAST",
825 => "THE PURGATION",
826 => "THE KEY",
827 => "THE PRINCESSS DILEMMA",
828 => "DARK CLOUDS AHEAD",
829 => "THE SMALLEST OF FAVORS",
830 => "SUMMONED BY SPIRITS",
831 => "EVIL ENTITIES",
832 => "ADOULIN CALLING",
833 => "THE DISAPPEARANCE OF NYLINE",
834 => "SHARED CONSCIOUSNESS",
835 => "CLEAR SKIES",
836 => "THE MAN IN BLACK",
837 => "TO THE VICTOR",
838 => "AN EXTRAORDINARY GENTLEMAN",
839 => "THE ORDERS TREASURES",
840 => "AUGUSTS HEIRLOOM",
841 => "BEAUTY AND THE BEAST",
842 => "WILDCAT WITH A GOLD PELT",
843 => "IN SEARCH OF ARCIELA",
844 => "LOOKING FOR LEADS",
845 => "DRIFTING NORTHWEST",
846 => "KUMHAU THE FLASHFROST NAAKUAL",
847 => "SOUL SIPHON",
848 => "STONEWALLED",
849 => "SALVATION",
850 => "GLIMMER OF PORTENT",
851 => "FIN"
 );

 
if (!empty($_SERVER['HTTP_CLIENT_IP'])) {
    $ip = $_SERVER['HTTP_CLIENT_IP'];
} elseif (!empty($_SERVER['HTTP_X_FORWARDED_FOR'])) {
    $ip = $_SERVER['HTTP_X_FORWARDED_FOR'];
} else {
    $ip = $_SERVER['REMOTE_ADDR'];
}


ini_set('display_errors',0);
ini_set('display_startup_errors',0);
error_reporting(0);


 